import type { AircraftCategory, WakeClass } from "./types";

export type AircraftModel =
  | "C172"
  | "PC12"
  | "C680"
  | "E175"
  | "AT76"
  | "Q400"
  | "A223"
  | "A320"
  | "B738"
  | "A21N"
  | "A333"
  | "A359"
  | "B789"
  | "B77W"
  | "B748"
  | "B76F"
  | "B77F";

export type AircraftFleetRole =
  | "general-aviation"
  | "utility"
  | "business"
  | "regional"
  | "narrowbody"
  | "widebody"
  | "cargo";

export type AircraftVisualFamily =
  | "ga-high-wing"
  | "utility-turboprop"
  | "business-jet"
  | "regional-jet"
  | "regional-high-wing-turboprop"
  | "airbus-narrowbody"
  | "boeing-narrowbody"
  | "airbus-widebody"
  | "boeing-widebody"
  | "jumbo"
  | "freighter";

export interface AircraftDataReference {
  id: string;
  publisher: string;
  title: string;
  url: string;
  kind: "manufacturer-product" | "manufacturer-planning";
  retrievedOn: string;
}

export const AIRCRAFT_DATA_REFERENCES: Record<string, AircraftDataReference> = {
  "cessna-skyhawk": {
    id: "cessna-skyhawk",
    publisher: "Textron Aviation",
    title: "Cessna Skyhawk specifications",
    url: "https://cessna.txtav.com/en/piston/cessna-skyhawk",
    kind: "manufacturer-product",
    retrievedOn: "2026-07-26",
  },
  "pilatus-pc12": {
    id: "pilatus-pc12",
    publisher: "Pilatus Aircraft",
    title: "PC-12 technical data",
    url: "https://www.pilatus-aircraft.com/en/pc-12/technical-data",
    kind: "manufacturer-product",
    retrievedOn: "2026-07-26",
  },
  "cessna-longitude": {
    id: "cessna-longitude",
    publisher: "Textron Aviation",
    title: "Citation Longitude specifications",
    url: "https://cessna.txtav.com/en/citation/longitude",
    kind: "manufacturer-product",
    retrievedOn: "2026-07-26",
  },
  "embraer-e175": {
    id: "embraer-e175",
    publisher: "Embraer Commercial Aviation",
    title: "E175 specification sheet",
    url: "https://www.embraercommercialaviation.com/wp-content/uploads/2017/06/Embraer_spec_E175_web-EN.pdf",
    kind: "manufacturer-product",
    retrievedOn: "2026-07-26",
  },
  "atr-72-600": {
    id: "atr-72-600",
    publisher: "ATR Aircraft",
    title: "ATR 72-600 specifications",
    url: "https://www.atr-aircraft.com/aircraft-services/aircraft-family/atr-72-600/",
    kind: "manufacturer-product",
    retrievedOn: "2026-07-26",
  },
  "dehavilland-dash8": {
    id: "dehavilland-dash8",
    publisher: "De Havilland Aircraft of Canada",
    title: "Dash 8-400 specification sheet",
    url: "https://dehavilland.com/wp-content/uploads/2025/03/DHC_Dash8_Spec-Sheet_v10_DIGITAL.pdf",
    kind: "manufacturer-product",
    retrievedOn: "2026-07-26",
  },
  "airbus-characteristics": {
    id: "airbus-characteristics",
    publisher: "Airbus",
    title: "Aircraft characteristics for airport and maintenance planning",
    url: "https://www.aircraft.airbus.com/en/customer-care/fleet-wide-care/airport-operations-and-aircraft-characteristics/aircraft-characteristics",
    kind: "manufacturer-planning",
    retrievedOn: "2026-07-26",
  },
  "airbus-a220": {
    id: "airbus-a220",
    publisher: "Airbus",
    title: "A220-300 technical data",
    url: "https://www.aircraft.airbus.com/en/aircraft/a220/a220-300",
    kind: "manufacturer-product",
    retrievedOn: "2026-07-26",
  },
  "boeing-characteristics": {
    id: "boeing-characteristics",
    publisher: "Boeing",
    title: "Airplane characteristics for airport planning",
    url: "https://www.boeing.com/commercial/airports",
    kind: "manufacturer-planning",
    retrievedOn: "2026-07-26",
  },
  "boeing-767": {
    id: "boeing-767",
    publisher: "Boeing",
    title: "767 airplane characteristics for airport planning",
    url: "https://www.boeing.com/content/dam/boeing/boeingdotcom/commercial/airports/acaps/767_REV_J.pdf",
    kind: "manufacturer-planning",
    retrievedOn: "2026-07-26",
  },
  "boeing-777": {
    id: "boeing-777",
    publisher: "Boeing",
    title: "777-200LR / 777-300ER airplane characteristics",
    url: "https://www.boeing.com/content/dam/boeing/boeingdotcom/commercial/airports/acaps/777_2lr_3er_f.pdf",
    kind: "manufacturer-planning",
    retrievedOn: "2026-07-26",
  },
  "boeing-748": {
    id: "boeing-748",
    publisher: "Boeing",
    title: "747-8 airplane characteristics for airport planning",
    url: "https://www.boeing.com/content/dam/boeing/boeingdotcom/commercial/airports/acaps/748_REV_C.pdf",
    kind: "manufacturer-planning",
    retrievedOn: "2026-07-26",
  },
};

export interface AircraftVisualSpec {
  family: AircraftVisualFamily;
  bodyRadius: number;
  bodyLength: number;
  wingSpan: number;
  wingSweep: number;
  tailHeight: number;
  engineRadius: number;
  engineLength: number;
  engineOffset: number;
  propeller?: boolean;
  engineMount?: "wing" | "nose" | "rear";
  wingMount?: "high" | "low";
  tailStyle?: "conventional" | "t-tail";
  winglets?: "none" | "fence" | "blended" | "raked";
  cargoDoor?: boolean;
  passengerWindows?: boolean;
}

/**
 * Manufacturer-referenced envelope data plus representative simulation values.
 * This catalog supports a game and is never a dispatch, loading, maintenance,
 * performance, or navigation source.
 */
export interface AircraftProfile {
  model: AircraftModel;
  manufacturer: string;
  name: string;
  category: AircraftCategory;
  fleetRole: AircraftFleetRole;
  wakeClass: WakeClass;
  lengthM: number;
  wingspanM: number;
  heightM: number;
  operatingEmptyWeightT: number;
  maxTakeoffWeightT: number;
  maxLandingWeightT: number;
  /** Modeled usable fuel mass for dispatch planning, not a certified loading figure. */
  usableFuelKg: number;
  /** Representative cruise fuel flow used by the deterministic planning model. */
  nominalCruiseFuelBurnKgPerHour: number;
  maximumRangeNm: number;
  cruiseKts: number;
  approachKts: number;
  rotationKts: number;
  taxiKts: number;
  taxiTurnKts: number;
  taxiAccelerationMps2: number;
  taxiBrakingMps2: number;
  taxiTurnRadiusM: number;
  minimumWingtipClearanceM: number;
  /** Modeled physical roll used by the fixed-step movement state. */
  takeoffRollM: number;
  /** Modeled physical roll used by the fixed-step movement state. */
  landingRollM: number;
  /** Conservative game-planning runway requirement, including operational margin. */
  takeoffRunwayRequiredM: number;
  /** Conservative game-planning runway requirement, including operational margin. */
  landingRunwayRequiredM: number;
  climbFpm: number;
  descentFpm: number;
  accelerationMps2: number;
  brakingMps2: number;
  turnRadiusM: number;
  wakeSeparationSeconds: number;
  /** Representative gate-to-ready time before the accelerated gameplay scale. */
  serviceMinutes: number;
  engines: number;
  engineType: "piston" | "turbofan" | "turboprop";
  dataReferenceIds: string[];
  auditedOn: string;
  visual: AircraftVisualSpec;
}

const AUDITED_ON = "2026-07-26";

export const AIRCRAFT_PROFILES: Record<AircraftModel, AircraftProfile> = {
  C172: {
    model: "C172",
    manufacturer: "Cessna",
    name: "172S Skyhawk",
    category: "regional",
    fleetRole: "general-aviation",
    wakeClass: "light",
    lengthM: 8.3,
    wingspanM: 11,
    heightM: 2.7,
    operatingEmptyWeightT: 0.762,
    maxTakeoffWeightT: 1.157,
    maxLandingWeightT: 1.157,
    usableFuelKg: 144,
    nominalCruiseFuelBurnKgPerHour: 38,
    maximumRangeNm: 640,
    cruiseKts: 124,
    approachKts: 60,
    rotationKts: 55,
    taxiKts: 8,
    taxiTurnKts: 5,
    taxiAccelerationMps2: 0.28,
    taxiBrakingMps2: 0.46,
    taxiTurnRadiusM: 6,
    minimumWingtipClearanceM: 2,
    takeoffRollM: 293,
    landingRollM: 175,
    takeoffRunwayRequiredM: 497,
    landingRunwayRequiredM: 407,
    climbFpm: 730,
    descentFpm: 700,
    accelerationMps2: 1.1,
    brakingMps2: 1.35,
    turnRadiusM: 260,
    wakeSeparationSeconds: 2.4,
    serviceMinutes: 10,
    engines: 1,
    engineType: "piston",
    dataReferenceIds: ["cessna-skyhawk"],
    auditedOn: AUDITED_ON,
    visual: {
      family: "ga-high-wing",
      bodyRadius: 0.26,
      bodyLength: 2.65,
      wingSpan: 3.8,
      wingSweep: 0.08,
      tailHeight: 0.72,
      engineRadius: 0.38,
      engineLength: 0.64,
      engineOffset: 0,
      propeller: true,
      engineMount: "nose",
      wingMount: "high",
      tailStyle: "conventional",
      winglets: "none",
      passengerWindows: true,
    },
  },
  PC12: {
    model: "PC12",
    manufacturer: "Pilatus",
    name: "PC-12 NGX utility turboprop",
    category: "regional",
    fleetRole: "utility",
    wakeClass: "light",
    lengthM: 14.4,
    wingspanM: 16.28,
    heightM: 4.26,
    operatingEmptyWeightT: 3.086,
    maxTakeoffWeightT: 4.74,
    maxLandingWeightT: 4.5,
    usableFuelKg: 1_227,
    nominalCruiseFuelBurnKgPerHour: 270,
    maximumRangeNm: 1_803,
    cruiseKts: 290,
    approachKts: 82,
    rotationKts: 82,
    taxiKts: 10,
    taxiTurnKts: 7,
    taxiAccelerationMps2: 0.42,
    taxiBrakingMps2: 0.58,
    taxiTurnRadiusM: 10,
    minimumWingtipClearanceM: 3,
    takeoffRollM: 758,
    landingRollM: 661,
    takeoffRunwayRequiredM: 758,
    landingRunwayRequiredM: 661,
    climbFpm: 1_920,
    descentFpm: 1_200,
    accelerationMps2: 1.45,
    brakingMps2: 1.55,
    turnRadiusM: 460,
    wakeSeparationSeconds: 2.8,
    serviceMinutes: 18,
    engines: 1,
    engineType: "turboprop",
    dataReferenceIds: ["pilatus-pc12"],
    auditedOn: AUDITED_ON,
    visual: {
      family: "utility-turboprop",
      bodyRadius: 0.38,
      bodyLength: 3.85,
      wingSpan: 4.75,
      wingSweep: 0.34,
      tailHeight: 0.96,
      engineRadius: 0.55,
      engineLength: 0.86,
      engineOffset: 0,
      propeller: true,
      engineMount: "nose",
      wingMount: "low",
      tailStyle: "t-tail",
      winglets: "blended",
      cargoDoor: true,
      passengerWindows: true,
    },
  },
  C680: {
    model: "C680",
    manufacturer: "Cessna",
    name: "Citation Longitude business jet",
    category: "regional",
    fleetRole: "business",
    wakeClass: "light",
    lengthM: 22.3,
    wingspanM: 21.01,
    heightM: 5.9,
    operatingEmptyWeightT: 10.705,
    maxTakeoffWeightT: 17.917,
    maxLandingWeightT: 15.195,
    usableFuelKg: 6_582,
    nominalCruiseFuelBurnKgPerHour: 1_050,
    maximumRangeNm: 3_500,
    cruiseKts: 483,
    approachKts: 110,
    rotationKts: 112,
    taxiKts: 12,
    taxiTurnKts: 8,
    taxiAccelerationMps2: 0.5,
    taxiBrakingMps2: 0.64,
    taxiTurnRadiusM: 13,
    minimumWingtipClearanceM: 3,
    takeoffRollM: 1_466,
    landingRollM: 966,
    takeoffRunwayRequiredM: 1_466,
    landingRunwayRequiredM: 966,
    climbFpm: 3_000,
    descentFpm: 1_800,
    accelerationMps2: 2.2,
    brakingMps2: 1.7,
    turnRadiusM: 650,
    wakeSeparationSeconds: 3,
    serviceMinutes: 25,
    engines: 2,
    engineType: "turbofan",
    dataReferenceIds: ["cessna-longitude"],
    auditedOn: AUDITED_ON,
    visual: {
      family: "business-jet",
      bodyRadius: 0.38,
      bodyLength: 4.8,
      wingSpan: 5.3,
      wingSweep: 0.6,
      tailHeight: 1.04,
      engineRadius: 0.34,
      engineLength: 1.08,
      engineOffset: 0.78,
      engineMount: "rear",
      wingMount: "low",
      tailStyle: "t-tail",
      winglets: "blended",
      passengerWindows: true,
    },
  },
  E175: {
    model: "E175",
    manufacturer: "Embraer",
    name: "E175 regional jet",
    category: "regional",
    fleetRole: "regional",
    wakeClass: "medium",
    lengthM: 31.7,
    wingspanM: 28.7,
    heightM: 9.86,
    operatingEmptyWeightT: 21.906,
    maxTakeoffWeightT: 40.37,
    maxLandingWeightT: 34.1,
    usableFuelKg: 9_335,
    nominalCruiseFuelBurnKgPerHour: 2_000,
    maximumRangeNm: 2_200,
    cruiseKts: 447,
    approachKts: 130,
    rotationKts: 128,
    taxiKts: 15,
    taxiTurnKts: 11,
    taxiAccelerationMps2: 0.55,
    taxiBrakingMps2: 0.68,
    taxiTurnRadiusM: 18,
    minimumWingtipClearanceM: 3,
    takeoffRollM: 1_650,
    landingRollM: 1_100,
    takeoffRunwayRequiredM: 2_244,
    landingRunwayRequiredM: 1_261,
    climbFpm: 2_500,
    descentFpm: 1_800,
    accelerationMps2: 2.2,
    brakingMps2: 1.8,
    turnRadiusM: 820,
    wakeSeparationSeconds: 3.4,
    serviceMinutes: 35,
    engines: 2,
    engineType: "turbofan",
    dataReferenceIds: ["embraer-e175"],
    auditedOn: AUDITED_ON,
    visual: {
      family: "regional-jet",
      bodyRadius: 0.43,
      bodyLength: 5.4,
      wingSpan: 6.2,
      wingSweep: 0.62,
      tailHeight: 1.08,
      engineRadius: 0.34,
      engineLength: 1.18,
      engineOffset: 1.7,
      engineMount: "wing",
      wingMount: "low",
      tailStyle: "conventional",
      winglets: "blended",
      passengerWindows: true,
    },
  },
  AT76: {
    model: "AT76",
    manufacturer: "ATR",
    name: "ATR 72-600 regional turboprop",
    category: "regional",
    fleetRole: "regional",
    wakeClass: "medium",
    lengthM: 27.17,
    wingspanM: 27.05,
    heightM: 7.65,
    operatingEmptyWeightT: 13.6,
    maxTakeoffWeightT: 23,
    maxLandingWeightT: 22.35,
    usableFuelKg: 5_000,
    nominalCruiseFuelBurnKgPerHour: 650,
    maximumRangeNm: 740,
    cruiseKts: 270,
    approachKts: 113,
    rotationKts: 112,
    taxiKts: 12,
    taxiTurnKts: 8,
    taxiAccelerationMps2: 0.46,
    taxiBrakingMps2: 0.62,
    taxiTurnRadiusM: 15,
    minimumWingtipClearanceM: 3,
    takeoffRollM: 1_315,
    landingRollM: 915,
    takeoffRunwayRequiredM: 1_315,
    landingRunwayRequiredM: 915,
    climbFpm: 1_355,
    descentFpm: 1_350,
    accelerationMps2: 1.55,
    brakingMps2: 1.65,
    turnRadiusM: 640,
    wakeSeparationSeconds: 3,
    serviceMinutes: 34,
    engines: 2,
    engineType: "turboprop",
    dataReferenceIds: ["atr-72-600"],
    auditedOn: AUDITED_ON,
    visual: {
      family: "regional-high-wing-turboprop",
      bodyRadius: 0.44,
      bodyLength: 5.05,
      wingSpan: 6.2,
      wingSweep: 0.2,
      tailHeight: 1.18,
      engineRadius: 0.48,
      engineLength: 0.82,
      engineOffset: 1.55,
      propeller: true,
      engineMount: "wing",
      wingMount: "high",
      tailStyle: "t-tail",
      winglets: "none",
      passengerWindows: true,
    },
  },
  Q400: {
    model: "Q400",
    manufacturer: "De Havilland Canada",
    name: "Dash 8-400 turboprop",
    category: "regional",
    fleetRole: "regional",
    wakeClass: "medium",
    lengthM: 32.8,
    wingspanM: 28.4,
    heightM: 8.36,
    operatingEmptyWeightT: 17.885,
    maxTakeoffWeightT: 29.574,
    maxLandingWeightT: 28.123,
    usableFuelKg: 5_318,
    nominalCruiseFuelBurnKgPerHour: 1_050,
    maximumRangeNm: 1_100,
    cruiseKts: 360,
    approachKts: 119,
    rotationKts: 116,
    taxiKts: 12,
    taxiTurnKts: 9,
    taxiAccelerationMps2: 0.48,
    taxiBrakingMps2: 0.64,
    taxiTurnRadiusM: 16,
    minimumWingtipClearanceM: 3,
    takeoffRollM: 1_390,
    landingRollM: 1_120,
    takeoffRunwayRequiredM: 1_425,
    landingRunwayRequiredM: 1_290,
    climbFpm: 2_000,
    descentFpm: 1_500,
    accelerationMps2: 1.7,
    brakingMps2: 1.7,
    turnRadiusM: 690,
    wakeSeparationSeconds: 3.1,
    serviceMinutes: 38,
    engines: 2,
    engineType: "turboprop",
    dataReferenceIds: ["dehavilland-dash8"],
    auditedOn: AUDITED_ON,
    visual: {
      family: "regional-high-wing-turboprop",
      bodyRadius: 0.46,
      bodyLength: 5.5,
      wingSpan: 6.35,
      wingSweep: 0.48,
      tailHeight: 1.12,
      engineRadius: 0.52,
      engineLength: 0.8,
      engineOffset: 1.45,
      propeller: true,
      engineMount: "wing",
      wingMount: "high",
      tailStyle: "t-tail",
      winglets: "none",
      passengerWindows: true,
    },
  },
  A223: {
    model: "A223",
    manufacturer: "Airbus",
    name: "A220-300",
    category: "narrowbody",
    fleetRole: "narrowbody",
    wakeClass: "medium",
    lengthM: 38.7,
    wingspanM: 35.1,
    heightM: 11.5,
    operatingEmptyWeightT: 37.1,
    maxTakeoffWeightT: 70.9,
    maxLandingWeightT: 61,
    usableFuelKg: 17_000,
    nominalCruiseFuelBurnKgPerHour: 2_150,
    maximumRangeNm: 3_400,
    cruiseKts: 447,
    approachKts: 133,
    rotationKts: 136,
    taxiKts: 17,
    taxiTurnKts: 10,
    taxiAccelerationMps2: 0.52,
    taxiBrakingMps2: 0.66,
    taxiTurnRadiusM: 21,
    minimumWingtipClearanceM: 4.5,
    takeoffRollM: 1_900,
    landingRollM: 1_420,
    takeoffRunwayRequiredM: 2_050,
    landingRunwayRequiredM: 1_550,
    climbFpm: 2_500,
    descentFpm: 1_900,
    accelerationMps2: 2.1,
    brakingMps2: 1.9,
    turnRadiusM: 980,
    wakeSeparationSeconds: 4,
    serviceMinutes: 46,
    engines: 2,
    engineType: "turbofan",
    dataReferenceIds: ["airbus-a220", "airbus-characteristics"],
    auditedOn: AUDITED_ON,
    visual: {
      family: "airbus-narrowbody",
      bodyRadius: 0.55,
      bodyLength: 6.5,
      wingSpan: 7.6,
      wingSweep: 0.7,
      tailHeight: 1.32,
      engineRadius: 0.52,
      engineLength: 1.48,
      engineOffset: 2.08,
      engineMount: "wing",
      wingMount: "low",
      tailStyle: "conventional",
      winglets: "fence",
      passengerWindows: true,
    },
  },
  A320: {
    model: "A320",
    manufacturer: "Airbus",
    name: "A320 narrowbody",
    category: "narrowbody",
    fleetRole: "narrowbody",
    wakeClass: "medium",
    lengthM: 37.6,
    wingspanM: 35.8,
    heightM: 11.76,
    operatingEmptyWeightT: 42.6,
    maxTakeoffWeightT: 78,
    maxLandingWeightT: 66,
    usableFuelKg: 19_000,
    nominalCruiseFuelBurnKgPerHour: 2_500,
    maximumRangeNm: 3_300,
    cruiseKts: 454,
    approachKts: 137,
    rotationKts: 142,
    taxiKts: 18,
    taxiTurnKts: 10,
    taxiAccelerationMps2: 0.5,
    taxiBrakingMps2: 0.66,
    taxiTurnRadiusM: 22,
    minimumWingtipClearanceM: 4.5,
    takeoffRollM: 2_100,
    landingRollM: 1_500,
    takeoffRunwayRequiredM: 2_300,
    landingRunwayRequiredM: 1_650,
    climbFpm: 2_300,
    descentFpm: 1_900,
    accelerationMps2: 2,
    brakingMps2: 1.9,
    turnRadiusM: 1_050,
    wakeSeparationSeconds: 4.2,
    serviceMinutes: 50,
    engines: 2,
    engineType: "turbofan",
    dataReferenceIds: ["airbus-characteristics"],
    auditedOn: AUDITED_ON,
    visual: {
      family: "airbus-narrowbody",
      bodyRadius: 0.58,
      bodyLength: 6.4,
      wingSpan: 7.7,
      wingSweep: 0.82,
      tailHeight: 1.28,
      engineRadius: 0.45,
      engineLength: 1.42,
      engineOffset: 2.05,
      engineMount: "wing",
      wingMount: "low",
      tailStyle: "conventional",
      winglets: "fence",
      passengerWindows: true,
    },
  },
  B738: {
    model: "B738",
    manufacturer: "Boeing",
    name: "737-800 narrowbody",
    category: "narrowbody",
    fleetRole: "narrowbody",
    wakeClass: "medium",
    lengthM: 39.5,
    wingspanM: 35.8,
    heightM: 12.55,
    operatingEmptyWeightT: 41.4,
    maxTakeoffWeightT: 79,
    maxLandingWeightT: 66.35,
    usableFuelKg: 20_900,
    nominalCruiseFuelBurnKgPerHour: 2_600,
    maximumRangeNm: 2_935,
    cruiseKts: 453,
    approachKts: 140,
    rotationKts: 145,
    taxiKts: 18,
    taxiTurnKts: 10,
    taxiAccelerationMps2: 0.48,
    taxiBrakingMps2: 0.64,
    taxiTurnRadiusM: 22,
    minimumWingtipClearanceM: 4.5,
    takeoffRollM: 2_250,
    landingRollM: 1_520,
    takeoffRunwayRequiredM: 2_450,
    landingRunwayRequiredM: 1_700,
    climbFpm: 2_400,
    descentFpm: 1_900,
    accelerationMps2: 2,
    brakingMps2: 1.9,
    turnRadiusM: 1_070,
    wakeSeparationSeconds: 4.3,
    serviceMinutes: 52,
    engines: 2,
    engineType: "turbofan",
    dataReferenceIds: ["boeing-characteristics"],
    auditedOn: AUDITED_ON,
    visual: {
      family: "boeing-narrowbody",
      bodyRadius: 0.59,
      bodyLength: 6.7,
      wingSpan: 7.9,
      wingSweep: 0.92,
      tailHeight: 1.31,
      engineRadius: 0.47,
      engineLength: 1.36,
      engineOffset: 2.15,
      engineMount: "wing",
      wingMount: "low",
      tailStyle: "conventional",
      winglets: "blended",
      passengerWindows: true,
    },
  },
  A21N: {
    model: "A21N",
    manufacturer: "Airbus",
    name: "A321neo narrowbody",
    category: "narrowbody",
    fleetRole: "narrowbody",
    wakeClass: "medium",
    lengthM: 44.51,
    wingspanM: 35.8,
    heightM: 11.76,
    operatingEmptyWeightT: 50.1,
    maxTakeoffWeightT: 97,
    maxLandingWeightT: 79.2,
    usableFuelKg: 20_500,
    nominalCruiseFuelBurnKgPerHour: 2_400,
    maximumRangeNm: 4_000,
    cruiseKts: 454,
    approachKts: 140,
    rotationKts: 150,
    taxiKts: 17,
    taxiTurnKts: 9.5,
    taxiAccelerationMps2: 0.46,
    taxiBrakingMps2: 0.63,
    taxiTurnRadiusM: 25,
    minimumWingtipClearanceM: 4.5,
    takeoffRollM: 2_300,
    landingRollM: 1_650,
    takeoffRunwayRequiredM: 2_550,
    landingRunwayRequiredM: 1_800,
    climbFpm: 2_200,
    descentFpm: 1_900,
    accelerationMps2: 1.9,
    brakingMps2: 1.8,
    turnRadiusM: 1_150,
    wakeSeparationSeconds: 4.5,
    serviceMinutes: 58,
    engines: 2,
    engineType: "turbofan",
    dataReferenceIds: ["airbus-characteristics"],
    auditedOn: AUDITED_ON,
    visual: {
      family: "airbus-narrowbody",
      bodyRadius: 0.59,
      bodyLength: 7.45,
      wingSpan: 7.9,
      wingSweep: 0.94,
      tailHeight: 1.34,
      engineRadius: 0.48,
      engineLength: 1.45,
      engineOffset: 2.16,
      engineMount: "wing",
      wingMount: "low",
      tailStyle: "conventional",
      winglets: "fence",
      passengerWindows: true,
    },
  },
  A333: {
    model: "A333",
    manufacturer: "Airbus",
    name: "A330-300 widebody",
    category: "widebody",
    fleetRole: "widebody",
    wakeClass: "heavy",
    lengthM: 63.66,
    wingspanM: 60.3,
    heightM: 16.79,
    operatingEmptyWeightT: 124.5,
    maxTakeoffWeightT: 242,
    maxLandingWeightT: 187,
    usableFuelKg: 76_560,
    nominalCruiseFuelBurnKgPerHour: 5_600,
    maximumRangeNm: 6_350,
    cruiseKts: 470,
    approachKts: 145,
    rotationKts: 153,
    taxiKts: 15,
    taxiTurnKts: 8,
    taxiAccelerationMps2: 0.39,
    taxiBrakingMps2: 0.55,
    taxiTurnRadiusM: 32,
    minimumWingtipClearanceM: 1.5,
    takeoffRollM: 2_700,
    landingRollM: 1_900,
    takeoffRunwayRequiredM: 2_950,
    landingRunwayRequiredM: 2_050,
    climbFpm: 1_900,
    descentFpm: 2_000,
    accelerationMps2: 1.55,
    brakingMps2: 1.55,
    turnRadiusM: 1_480,
    wakeSeparationSeconds: 6.1,
    serviceMinutes: 88,
    engines: 2,
    engineType: "turbofan",
    dataReferenceIds: ["airbus-characteristics"],
    auditedOn: AUDITED_ON,
    visual: {
      family: "airbus-widebody",
      bodyRadius: 0.75,
      bodyLength: 8.55,
      wingSpan: 10.1,
      wingSweep: 1.16,
      tailHeight: 1.67,
      engineRadius: 0.62,
      engineLength: 1.74,
      engineOffset: 2.68,
      engineMount: "wing",
      wingMount: "low",
      tailStyle: "conventional",
      winglets: "fence",
      passengerWindows: true,
    },
  },
  A359: {
    model: "A359",
    manufacturer: "Airbus",
    name: "A350-900 widebody",
    category: "widebody",
    fleetRole: "widebody",
    wakeClass: "heavy",
    lengthM: 66.8,
    wingspanM: 64.8,
    heightM: 17.05,
    operatingEmptyWeightT: 142.4,
    maxTakeoffWeightT: 280,
    maxLandingWeightT: 207,
    usableFuelKg: 110_500,
    nominalCruiseFuelBurnKgPerHour: 5_800,
    maximumRangeNm: 8_100,
    cruiseKts: 488,
    approachKts: 145,
    rotationKts: 155,
    taxiKts: 15,
    taxiTurnKts: 8,
    taxiAccelerationMps2: 0.38,
    taxiBrakingMps2: 0.55,
    taxiTurnRadiusM: 34,
    minimumWingtipClearanceM: 1.5,
    takeoffRollM: 2_650,
    landingRollM: 1_850,
    takeoffRunwayRequiredM: 2_900,
    landingRunwayRequiredM: 2_050,
    climbFpm: 2_000,
    descentFpm: 2_100,
    accelerationMps2: 1.6,
    brakingMps2: 1.6,
    turnRadiusM: 1_520,
    wakeSeparationSeconds: 6.2,
    serviceMinutes: 92,
    engines: 2,
    engineType: "turbofan",
    dataReferenceIds: ["airbus-characteristics"],
    auditedOn: AUDITED_ON,
    visual: {
      family: "airbus-widebody",
      bodyRadius: 0.74,
      bodyLength: 8.8,
      wingSpan: 10.5,
      wingSweep: 1.25,
      tailHeight: 1.7,
      engineRadius: 0.62,
      engineLength: 1.76,
      engineOffset: 2.75,
      engineMount: "wing",
      wingMount: "low",
      tailStyle: "conventional",
      winglets: "raked",
      passengerWindows: true,
    },
  },
  B789: {
    model: "B789",
    manufacturer: "Boeing",
    name: "787-9 Dreamliner",
    category: "widebody",
    fleetRole: "widebody",
    wakeClass: "heavy",
    lengthM: 62.8,
    wingspanM: 60.1,
    heightM: 17,
    operatingEmptyWeightT: 128.9,
    maxTakeoffWeightT: 254,
    maxLandingWeightT: 192.8,
    usableFuelKg: 101_500,
    nominalCruiseFuelBurnKgPerHour: 5_600,
    maximumRangeNm: 7_565,
    cruiseKts: 488,
    approachKts: 142,
    rotationKts: 158,
    taxiKts: 15,
    taxiTurnKts: 8,
    taxiAccelerationMps2: 0.4,
    taxiBrakingMps2: 0.56,
    taxiTurnRadiusM: 32,
    minimumWingtipClearanceM: 1.5,
    takeoffRollM: 2_550,
    landingRollM: 1_800,
    takeoffRunwayRequiredM: 2_850,
    landingRunwayRequiredM: 2_000,
    climbFpm: 2_100,
    descentFpm: 2_000,
    accelerationMps2: 1.7,
    brakingMps2: 1.6,
    turnRadiusM: 1_470,
    wakeSeparationSeconds: 6,
    serviceMinutes: 90,
    engines: 2,
    engineType: "turbofan",
    dataReferenceIds: ["boeing-characteristics"],
    auditedOn: AUDITED_ON,
    visual: {
      family: "boeing-widebody",
      bodyRadius: 0.72,
      bodyLength: 8.5,
      wingSpan: 10,
      wingSweep: 1.16,
      tailHeight: 1.64,
      engineRadius: 0.6,
      engineLength: 1.7,
      engineOffset: 2.65,
      engineMount: "wing",
      wingMount: "low",
      tailStyle: "conventional",
      winglets: "raked",
      passengerWindows: true,
    },
  },
  B77W: {
    model: "B77W",
    manufacturer: "Boeing",
    name: "777-300ER widebody",
    category: "widebody",
    fleetRole: "widebody",
    wakeClass: "heavy",
    lengthM: 73.9,
    wingspanM: 64.8,
    heightM: 18.5,
    operatingEmptyWeightT: 167.8,
    maxTakeoffWeightT: 351.5,
    maxLandingWeightT: 251.3,
    usableFuelKg: 145_500,
    nominalCruiseFuelBurnKgPerHour: 7_500,
    maximumRangeNm: 7_370,
    cruiseKts: 490,
    approachKts: 150,
    rotationKts: 160,
    taxiKts: 14,
    taxiTurnKts: 7.5,
    taxiAccelerationMps2: 0.35,
    taxiBrakingMps2: 0.52,
    taxiTurnRadiusM: 38,
    minimumWingtipClearanceM: 1.5,
    takeoffRollM: 3_050,
    landingRollM: 2_050,
    takeoffRunwayRequiredM: 3_250,
    landingRunwayRequiredM: 2_250,
    climbFpm: 1_850,
    descentFpm: 1_800,
    accelerationMps2: 1.4,
    brakingMps2: 1.42,
    turnRadiusM: 1_660,
    wakeSeparationSeconds: 7.1,
    serviceMinutes: 105,
    engines: 2,
    engineType: "turbofan",
    dataReferenceIds: ["boeing-777"],
    auditedOn: AUDITED_ON,
    visual: {
      family: "boeing-widebody",
      bodyRadius: 0.82,
      bodyLength: 9.65,
      wingSpan: 10.9,
      wingSweep: 1.34,
      tailHeight: 1.83,
      engineRadius: 0.72,
      engineLength: 2,
      engineOffset: 2.9,
      engineMount: "wing",
      wingMount: "low",
      tailStyle: "conventional",
      winglets: "raked",
      passengerWindows: true,
    },
  },
  B748: {
    model: "B748",
    manufacturer: "Boeing",
    name: "747-8 Intercontinental",
    category: "widebody",
    fleetRole: "widebody",
    wakeClass: "heavy",
    lengthM: 76.3,
    wingspanM: 68.4,
    heightM: 19.4,
    operatingEmptyWeightT: 220.1,
    maxTakeoffWeightT: 447.7,
    maxLandingWeightT: 346.1,
    usableFuelKg: 191_565,
    nominalCruiseFuelBurnKgPerHour: 10_500,
    maximumRangeNm: 7_730,
    cruiseKts: 493,
    approachKts: 153,
    rotationKts: 170,
    taxiKts: 13,
    taxiTurnKts: 7,
    taxiAccelerationMps2: 0.31,
    taxiBrakingMps2: 0.49,
    taxiTurnRadiusM: 42,
    minimumWingtipClearanceM: 1.5,
    takeoffRollM: 3_200,
    landingRollM: 2_150,
    takeoffRunwayRequiredM: 3_400,
    landingRunwayRequiredM: 2_350,
    climbFpm: 1_700,
    descentFpm: 1_700,
    accelerationMps2: 1.25,
    brakingMps2: 1.35,
    turnRadiusM: 1_780,
    wakeSeparationSeconds: 7.6,
    serviceMinutes: 120,
    engines: 4,
    engineType: "turbofan",
    dataReferenceIds: ["boeing-748"],
    auditedOn: AUDITED_ON,
    visual: {
      family: "jumbo",
      bodyRadius: 0.86,
      bodyLength: 9.8,
      wingSpan: 11.5,
      wingSweep: 1.42,
      tailHeight: 1.95,
      engineRadius: 0.67,
      engineLength: 1.9,
      engineOffset: 3.15,
      engineMount: "wing",
      wingMount: "low",
      tailStyle: "conventional",
      winglets: "raked",
      passengerWindows: true,
    },
  },
  B76F: {
    model: "B76F",
    manufacturer: "Boeing",
    name: "767-300 Freighter",
    category: "cargo",
    fleetRole: "cargo",
    wakeClass: "heavy",
    lengthM: 54.94,
    wingspanM: 47.57,
    heightM: 15.85,
    operatingEmptyWeightT: 86.2,
    maxTakeoffWeightT: 186.88,
    maxLandingWeightT: 145.15,
    usableFuelKg: 73_000,
    nominalCruiseFuelBurnKgPerHour: 5_000,
    maximumRangeNm: 3_255,
    cruiseKts: 459,
    approachKts: 145,
    rotationKts: 151,
    taxiKts: 15,
    taxiTurnKts: 8,
    taxiAccelerationMps2: 0.4,
    taxiBrakingMps2: 0.56,
    taxiTurnRadiusM: 30,
    minimumWingtipClearanceM: 1.5,
    takeoffRollM: 2_600,
    landingRollM: 1_800,
    takeoffRunwayRequiredM: 2_900,
    landingRunwayRequiredM: 2_000,
    climbFpm: 1_900,
    descentFpm: 1_800,
    accelerationMps2: 1.55,
    brakingMps2: 1.55,
    turnRadiusM: 1_420,
    wakeSeparationSeconds: 5.8,
    serviceMinutes: 92,
    engines: 2,
    engineType: "turbofan",
    dataReferenceIds: ["boeing-767"],
    auditedOn: AUDITED_ON,
    visual: {
      family: "freighter",
      bodyRadius: 0.7,
      bodyLength: 8.05,
      wingSpan: 9.1,
      wingSweep: 1.14,
      tailHeight: 1.62,
      engineRadius: 0.6,
      engineLength: 1.7,
      engineOffset: 2.55,
      engineMount: "wing",
      wingMount: "low",
      tailStyle: "conventional",
      winglets: "blended",
      cargoDoor: true,
      passengerWindows: false,
    },
  },
  B77F: {
    model: "B77F",
    manufacturer: "Boeing",
    name: "777 Freighter",
    category: "cargo",
    fleetRole: "cargo",
    wakeClass: "heavy",
    lengthM: 63.7,
    wingspanM: 64.8,
    heightM: 18.6,
    operatingEmptyWeightT: 144.4,
    maxTakeoffWeightT: 347.8,
    maxLandingWeightT: 261.5,
    usableFuelKg: 145_500,
    nominalCruiseFuelBurnKgPerHour: 8_200,
    maximumRangeNm: 4_970,
    cruiseKts: 490,
    approachKts: 149,
    rotationKts: 160,
    taxiKts: 14,
    taxiTurnKts: 7.5,
    taxiAccelerationMps2: 0.36,
    taxiBrakingMps2: 0.52,
    taxiTurnRadiusM: 35,
    minimumWingtipClearanceM: 1.5,
    takeoffRollM: 3_050,
    landingRollM: 2_050,
    takeoffRunwayRequiredM: 3_250,
    landingRunwayRequiredM: 2_250,
    climbFpm: 1_800,
    descentFpm: 1_700,
    accelerationMps2: 1.4,
    brakingMps2: 1.4,
    turnRadiusM: 1_600,
    wakeSeparationSeconds: 7,
    serviceMinutes: 110,
    engines: 2,
    engineType: "turbofan",
    dataReferenceIds: ["boeing-777"],
    auditedOn: AUDITED_ON,
    visual: {
      family: "freighter",
      bodyRadius: 0.8,
      bodyLength: 9,
      wingSpan: 10.9,
      wingSweep: 1.3,
      tailHeight: 1.78,
      engineRadius: 0.7,
      engineLength: 1.92,
      engineOffset: 2.85,
      engineMount: "wing",
      wingMount: "low",
      tailStyle: "conventional",
      winglets: "raked",
      cargoDoor: true,
      passengerWindows: false,
    },
  },
};

export const AIRCRAFT_ROSTER = Object.keys(
  AIRCRAFT_PROFILES,
) as AircraftModel[];

export function aircraftProfile(model: AircraftModel): AircraftProfile {
  return AIRCRAFT_PROFILES[model];
}
