export type FighterEra =
  "World War II" | "Early jet age" | "Cold War" | "Modern";

export type FighterPropulsion = "piston" | "rocket" | "turbojet" | "turbofan";

export type FighterRole =
  | "day fighter"
  | "night fighter"
  | "interceptor"
  | "escort fighter"
  | "naval fighter"
  | "air superiority"
  | "multirole"
  | "light fighter"
  | "fighter-bomber";

export type FighterStatus =
  "historic" | "operational" | "limited service" | "prototype / development";

export type FighterVisualFamily =
  | "biplane"
  | "inline-prop"
  | "radial-prop"
  | "twin-prop"
  | "twin-boom-prop"
  | "push-pull-prop"
  | "rocket-interceptor"
  | "straight-jet"
  | "twin-boom-jet"
  | "swept-single-jet"
  | "swept-twin-jet"
  | "delta-jet"
  | "canard-delta"
  | "variable-sweep"
  | "vtol"
  | "stealth"
  | "tailless";

export type WingPlanform =
  | "straight"
  | "tapered"
  | "elliptical"
  | "swept"
  | "delta"
  | "cropped-delta"
  | "variable"
  | "forward-swept";

export type FighterTail = "single" | "twin" | "v-tail" | "none";

export type FighterIntake =
  "none" | "nose" | "chin" | "side" | "wing-root" | "ventral";

export interface FighterVisualDesign {
  family: FighterVisualFamily;
  wing: WingPlanform;
  tail: FighterTail;
  intake: FighterIntake;
  sweepDeg: number;
  canards?: boolean;
  twinBoom?: boolean;
  biplane?: boolean;
  wingPods?: boolean;
  naval?: boolean;
  faceted?: boolean;
  dorsalIntake?: boolean;
  horizontalTail?: boolean;
  pusher?: boolean;
}

export interface FighterProfile {
  id: string;
  name: string;
  manufacturer: string;
  designNation: string;
  firstFlight: number;
  era: FighterEra;
  propulsion: FighterPropulsion;
  role: FighterRole;
  status: FighterStatus;
  lengthM: number;
  wingspanM: number;
  maxSpeedKph: number;
  serviceCeilingM: number;
  engines: number;
  crew: number;
  visual: FighterVisualDesign;
  variants: string[];
  operators: string[];
  summary: string;
  referenceIds: string[];
}

export interface FighterDataReference {
  id: string;
  publisher: string;
  title: string;
  url: string;
  kind: "museum" | "manufacturer" | "program";
  retrievedOn: string;
}

export const FIGHTER_DATA_REFERENCES: Record<string, FighterDataReference> = {
  "usaf-museum": {
    id: "usaf-museum",
    publisher: "National Museum of the United States Air Force",
    title: "Aircraft fact sheets and collections",
    url: "https://www.nationalmuseum.af.mil/Visit/Museum-Exhibits/Fact-Sheets/",
    kind: "museum",
    retrievedOn: "2026-07-27",
  },
  "raf-museum": {
    id: "raf-museum",
    publisher: "Royal Air Force Museum",
    title: "Aircraft research collection",
    url: "https://www.rafmuseum.org.uk/research/collections/",
    kind: "museum",
    retrievedOn: "2026-07-27",
  },
  smithsonian: {
    id: "smithsonian",
    publisher: "Smithsonian National Air and Space Museum",
    title: "Aircraft collection",
    url: "https://airandspace.si.edu/collection-objects",
    kind: "museum",
    retrievedOn: "2026-07-27",
  },
  "nnam-corsair": {
    id: "nnam-corsair",
    publisher: "National Naval Aviation Museum",
    title: "FG-1D Corsair collection record",
    url: "https://www.history.navy.mil/content/history/museums/nnam/explore/collections/aircraft/f/fg-1d-corsair.html",
    kind: "museum",
    retrievedOn: "2026-07-28",
  },
  "nmusaf-p51d": {
    id: "nmusaf-p51d",
    publisher: "National Museum of the United States Air Force",
    title: "North American P-51D Mustang fact sheet",
    url: "https://www.nationalmuseum.af.mil/Visit/Museum-Exhibits/Fact-Sheets/Display/Article/196263/north-american-p-51d-mustang/",
    kind: "museum",
    retrievedOn: "2026-07-28",
  },
  "nmusaf-f86": {
    id: "nmusaf-f86",
    publisher: "National Museum of the United States Air Force",
    title: "North American F-86A Sabre fact sheet",
    url: "https://www.nationalmuseum.af.mil/Visit/Museum-Exhibits/Fact-Sheets/Display/Article/196118/north-american-f-86a-sabre/",
    kind: "museum",
    retrievedOn: "2026-07-28",
  },
  "f35-program": {
    id: "f35-program",
    publisher: "Lockheed Martin",
    title: "F-35 Lightning II fast facts",
    url: "https://www.lockheedmartin.com/en-us/products/f-35.html",
    kind: "manufacturer",
    retrievedOn: "2026-07-27",
  },
  "usaf-f35a": {
    id: "usaf-f35a",
    publisher: "United States Air Force",
    title: "F-35A Lightning II fact sheet",
    url: "https://www.af.mil/About-Us/Fact-Sheets/Display/Article/478441/f-35a-lightning-ii-conventional-takeoff-and-landing-variant/",
    kind: "program",
    retrievedOn: "2026-07-27",
  },
  "china-mod-j20": {
    id: "china-mod-j20",
    publisher: "Ministry of National Defense of the People's Republic of China",
    title: "10th anniversary of J-20's maiden flight",
    url: "https://eng.mod.gov.cn/xb/News_213114/TopStories/4876978.html",
    kind: "program",
    retrievedOn: "2026-07-27",
  },
  "usaf-f22": {
    id: "usaf-f22",
    publisher: "United States Air Force",
    title: "F-22 Raptor fact sheet",
    url: "https://www.af.mil/About-Us/Fact-Sheets/Display/Article/104506/f-22-raptor/",
    kind: "program",
    retrievedOn: "2026-07-27",
  },
  "uac-mig35": {
    id: "uac-mig35",
    publisher: "United Aircraft Corporation",
    title: "MiG-35 flight specifications",
    url: "https://uacrussia.ru/en/aircraft/lineup/military/mig-35/",
    kind: "manufacturer",
    retrievedOn: "2026-07-27",
  },
  "roe-mig35": {
    id: "roe-mig35",
    publisher: "Rosoboronexport",
    title: "MiG-35/35D public product sheet",
    url: "https://roe.ru/pdfs/pdf_6930.pdf",
    kind: "manufacturer",
    retrievedOn: "2026-07-27",
  },
  "boeing-fighters": {
    id: "boeing-fighters",
    publisher: "Boeing",
    title: "Fighters and bombers",
    url: "https://www.boeing.com/defense/fighters-and-bombers",
    kind: "manufacturer",
    retrievedOn: "2026-07-27",
  },
  dassault: {
    id: "dassault",
    publisher: "Dassault Aviation",
    title: "Military aircraft programs",
    url: "https://www.dassault-aviation.com/en/group/about-us/civil-and-military-aircraft/",
    kind: "manufacturer",
    retrievedOn: "2026-07-27",
  },
  saab: {
    id: "saab",
    publisher: "Saab",
    title: "Gripen fighter family",
    url: "https://www.saab.com/products/gripen-e-series",
    kind: "manufacturer",
    retrievedOn: "2026-07-27",
  },
  eurofighter: {
    id: "eurofighter",
    publisher: "Eurofighter Jagdflugzeug GmbH",
    title: "Eurofighter Typhoon program and aircraft",
    url: "https://world.eurofighter.com/",
    kind: "program",
    retrievedOn: "2026-07-27",
  },
  hal: {
    id: "hal",
    publisher: "Hindustan Aeronautics Limited",
    title: "Light Combat Aircraft Tejas",
    url: "https://www.hal-india.co.in/product/lca",
    kind: "manufacturer",
    retrievedOn: "2026-07-27",
  },
};

const designs = {
  biplane: design("biplane", "straight", "single", "none", 0, {
    biplane: true,
  }),
  inline: design("inline-prop", "tapered", "single", "chin", 4),
  inlineElliptical: design("inline-prop", "elliptical", "single", "chin", 2),
  radial: design("radial-prop", "tapered", "single", "none", 3),
  radialElliptical: design("radial-prop", "elliptical", "single", "none", 2),
  twinProp: design("twin-prop", "tapered", "single", "none", 4),
  twinPropTwinTail: design("twin-prop", "tapered", "twin", "none", 4),
  twinBoomProp: design("twin-boom-prop", "tapered", "twin", "none", 3, {
    twinBoom: true,
  }),
  pushPull: design("push-pull-prop", "tapered", "single", "none", 3),
  rocket: design("rocket-interceptor", "swept", "single", "none", 24, {
    horizontalTail: false,
  }),
  straightJet: design("straight-jet", "straight", "single", "nose", 2),
  straightTwinJet: design("straight-jet", "straight", "single", "side", 3, {
    wingPods: true,
  }),
  twinBoomJet: design("twin-boom-jet", "straight", "twin", "wing-root", 2, {
    twinBoom: true,
  }),
  sweptSingle: design("swept-single-jet", "swept", "single", "nose", 35),
  sweptSingleSide: design("swept-single-jet", "swept", "single", "side", 35),
  sweptTwin: design("swept-twin-jet", "swept", "twin", "side", 38),
  delta: design("delta-jet", "delta", "single", "side", 56, {
    horizontalTail: false,
  }),
  croppedDelta: design("delta-jet", "cropped-delta", "single", "side", 48),
  canardDelta: design("canard-delta", "delta", "single", "side", 55, {
    canards: true,
    horizontalTail: false,
  }),
  variable: design("variable-sweep", "variable", "twin", "side", 45),
  vtol: design("vtol", "swept", "single", "side", 35),
  stealthTwin: design("stealth", "cropped-delta", "twin", "side", 42, {
    faceted: true,
  }),
  stealthSingle: design("stealth", "cropped-delta", "twin", "side", 38, {
    faceted: true,
  }),
  tailless: design("tailless", "delta", "none", "side", 62, {
    faceted: true,
    horizontalTail: false,
  }),
  facetedVtail: design("stealth", "delta", "v-tail", "side", 62, {
    faceted: true,
    horizontalTail: false,
  }),
  forwardSwept: design(
    "swept-single-jet",
    "forward-swept",
    "single",
    "side",
    -28,
  ),
} as const;

interface FighterOptions {
  role?: FighterRole;
  status?: FighterStatus;
  variants?: string[];
  operators?: string[];
  summary?: string;
  references?: string[];
  visual?: Partial<FighterVisualDesign>;
}

function design(
  family: FighterVisualFamily,
  wing: WingPlanform,
  tail: FighterTail,
  intake: FighterIntake,
  sweepDeg: number,
  extras: Partial<FighterVisualDesign> = {},
): FighterVisualDesign {
  return { family, wing, tail, intake, sweepDeg, ...extras };
}

function f(
  id: string,
  name: string,
  manufacturer: string,
  designNation: string,
  firstFlight: number,
  era: FighterEra,
  propulsion: FighterPropulsion,
  lengthM: number,
  wingspanM: number,
  maxSpeedKph: number,
  serviceCeilingM: number,
  engines: number,
  crew: number,
  baseVisual: FighterVisualDesign,
  options: FighterOptions = {},
): FighterProfile {
  const status =
    options.status ?? (era === "Modern" ? "operational" : "historic");
  const role = options.role ?? defaultRole(era, baseVisual, crew);
  return {
    id,
    name,
    manufacturer,
    designNation,
    firstFlight,
    era,
    propulsion,
    role,
    status,
    lengthM,
    wingspanM,
    maxSpeedKph,
    serviceCeilingM,
    engines,
    crew,
    visual: { ...baseVisual, ...options.visual },
    variants: options.variants ?? [],
    operators: options.operators ?? [designNation],
    summary:
      options.summary ??
      `${designNation} ${role} first flown in ${firstFlight}.`,
    referenceIds: options.references ?? referencesFor(designNation, era),
  };
}

function defaultRole(
  era: FighterEra,
  visual: FighterVisualDesign,
  crew: number,
): FighterRole {
  if (crew > 1 && era === "World War II") return "night fighter";
  if (visual.naval) return "naval fighter";
  if (era === "Modern") return "multirole";
  if (era === "Cold War" || era === "Early jet age") return "interceptor";
  return "day fighter";
}

function referencesFor(nation: string, era: FighterEra): string[] {
  if (era === "Modern") {
    if (nation === "France") return ["dassault"];
    if (nation === "Sweden") return ["saab"];
    if (nation === "India") return ["hal"];
    if (nation === "European consortium") return ["eurofighter"];
    if (nation === "United States") return ["f35-program", "boeing-fighters"];
  }
  if (nation === "United Kingdom") return ["raf-museum"];
  if (nation === "United States") return ["usaf-museum", "smithsonian"];
  return ["smithsonian", "raf-museum"];
}

const WWII: FighterProfile[] = [
  // United States
  f(
    "p-26",
    "P-26 Peashooter",
    "Boeing",
    "United States",
    1932,
    "World War II",
    "piston",
    7.19,
    8.52,
    377,
    8350,
    1,
    1,
    designs.radial,
  ),
  f(
    "p-35",
    "P-35",
    "Seversky",
    "United States",
    1935,
    "World War II",
    "piston",
    8.17,
    10.97,
    467,
    9570,
    1,
    1,
    designs.radial,
  ),
  f(
    "p-36",
    "P-36 Hawk",
    "Curtiss",
    "United States",
    1935,
    "World War II",
    "piston",
    8.69,
    11.38,
    504,
    10000,
    1,
    1,
    designs.radial,
    { variants: ["Hawk 75", "P-36A/C"] },
  ),
  f(
    "p-38",
    "P-38 Lightning",
    "Lockheed",
    "United States",
    1939,
    "World War II",
    "piston",
    11.53,
    15.85,
    667,
    13400,
    2,
    1,
    designs.twinBoomProp,
    { role: "escort fighter", variants: ["P-38F/J/L"] },
  ),
  f(
    "p-39",
    "P-39 Airacobra",
    "Bell",
    "United States",
    1938,
    "World War II",
    "piston",
    9.19,
    10.36,
    626,
    10700,
    1,
    1,
    designs.inline,
    { variants: ["P-39D", "P-39N/Q"] },
  ),
  f(
    "p-63",
    "P-63 Kingcobra",
    "Bell",
    "United States",
    1942,
    "World War II",
    "piston",
    9.96,
    11.68,
    660,
    13100,
    1,
    1,
    designs.inline,
    { variants: ["P-63A/C/F"] },
  ),
  f(
    "p-40",
    "P-40 Warhawk",
    "Curtiss",
    "United States",
    1938,
    "World War II",
    "piston",
    9.66,
    11.38,
    580,
    8900,
    1,
    1,
    designs.inline,
    { variants: ["Tomahawk", "Kittyhawk", "P-40E/N"] },
  ),
  f(
    "p-47",
    "P-47 Thunderbolt",
    "Republic",
    "United States",
    1941,
    "World War II",
    "piston",
    11.0,
    12.43,
    697,
    13100,
    1,
    1,
    designs.radial,
    {
      role: "fighter-bomber",
      variants: ["P-47D Razorback", "P-47D Bubbletop", "P-47N"],
    },
  ),
  f(
    "p-51",
    "P-51 Mustang",
    "North American",
    "United States",
    1940,
    "World War II",
    "piston",
    9.83,
    11.28,
    703,
    12770,
    1,
    1,
    designs.inline,
    {
      role: "escort fighter",
      variants: ["P-51B/C", "P-51D/K", "P-51H"],
      references: ["nmusaf-p51d", "smithsonian"],
    },
  ),
  f(
    "f2a",
    "F2A Buffalo",
    "Brewster",
    "United States",
    1937,
    "World War II",
    "piston",
    8.03,
    10.67,
    517,
    10100,
    1,
    1,
    designs.radial,
    { role: "naval fighter", visual: { naval: true } },
  ),
  f(
    "f4f",
    "F4F Wildcat",
    "Grumman",
    "United States",
    1937,
    "World War II",
    "piston",
    8.76,
    11.58,
    533,
    12000,
    1,
    1,
    designs.radial,
    {
      role: "naval fighter",
      variants: ["F4F-3", "F4F-4", "FM-2"],
      visual: { naval: true },
    },
  ),
  f(
    "f6f",
    "F6F Hellcat",
    "Grumman",
    "United States",
    1942,
    "World War II",
    "piston",
    10.24,
    13.06,
    611,
    11370,
    1,
    1,
    designs.radial,
    {
      role: "naval fighter",
      variants: ["F6F-3", "F6F-5"],
      visual: { naval: true },
    },
  ),
  f(
    "f4u",
    "F4U Corsair",
    "Vought",
    "United States",
    1940,
    "World War II",
    "piston",
    10.26,
    12.5,
    718,
    12650,
    1,
    1,
    designs.radial,
    {
      role: "naval fighter",
      variants: ["F4U-1", "F4U-4", "FG-1"],
      references: ["nnam-corsair", "smithsonian"],
      visual: { naval: true, wing: "elliptical" },
    },
  ),
  f(
    "f7f",
    "F7F Tigercat",
    "Grumman",
    "United States",
    1943,
    "World War II",
    "piston",
    13.83,
    15.7,
    740,
    12300,
    2,
    1,
    designs.twinProp,
    {
      role: "naval fighter",
      variants: ["F7F-1", "F7F-3", "F7F-3N"],
      visual: { naval: true },
    },
  ),
  f(
    "f8f",
    "F8F Bearcat",
    "Grumman",
    "United States",
    1944,
    "World War II",
    "piston",
    8.61,
    10.92,
    732,
    11700,
    1,
    1,
    designs.radial,
    {
      role: "naval fighter",
      variants: ["F8F-1", "F8F-2"],
      visual: { naval: true },
    },
  ),
  f(
    "p-61",
    "P-61 Black Widow",
    "Northrop",
    "United States",
    1942,
    "World War II",
    "piston",
    15.11,
    20.12,
    589,
    10100,
    2,
    3,
    designs.twinBoomProp,
    { role: "night fighter" },
  ),
  f(
    "p-59",
    "P-59 Airacomet",
    "Bell",
    "United States",
    1942,
    "World War II",
    "turbojet",
    11.84,
    13.87,
    665,
    14080,
    2,
    1,
    designs.straightTwinJet,
    {
      role: "day fighter",
      status: "prototype / development",
      summary:
        "The first United States jet fighter, used for service evaluation during World War II.",
    },
  ),

  // United Kingdom and Commonwealth
  f(
    "gladiator",
    "Gloster Gladiator",
    "Gloster",
    "United Kingdom",
    1934,
    "World War II",
    "piston",
    8.36,
    9.83,
    414,
    10000,
    1,
    1,
    designs.biplane,
    { variants: ["Gladiator Mk I/II", "Sea Gladiator"] },
  ),
  f(
    "hurricane",
    "Hawker Hurricane",
    "Hawker",
    "United Kingdom",
    1935,
    "World War II",
    "piston",
    9.84,
    12.19,
    547,
    10970,
    1,
    1,
    designs.inlineElliptical,
    { variants: ["Mk I", "Mk IIC", "Sea Hurricane"] },
  ),
  f(
    "spitfire",
    "Supermarine Spitfire",
    "Supermarine",
    "United Kingdom",
    1936,
    "World War II",
    "piston",
    9.12,
    11.23,
    594,
    11280,
    1,
    1,
    designs.inlineElliptical,
    {
      variants: ["Mk I/V/IX/XIV", "Seafire", "F.24"],
      summary:
        "Elliptical-wing British fighter family developed continuously from Merlin to Griffon power.",
    },
  ),
  f(
    "defiant",
    "Boulton Paul Defiant",
    "Boulton Paul",
    "United Kingdom",
    1937,
    "World War II",
    "piston",
    10.77,
    11.99,
    489,
    9250,
    1,
    2,
    designs.inline,
    { role: "night fighter" },
  ),
  f(
    "whirlwind",
    "Westland Whirlwind",
    "Westland",
    "United Kingdom",
    1938,
    "World War II",
    "piston",
    9.83,
    13.72,
    580,
    9200,
    2,
    1,
    designs.twinProp,
  ),
  f(
    "beaufighter",
    "Bristol Beaufighter",
    "Bristol",
    "United Kingdom",
    1939,
    "World War II",
    "piston",
    12.7,
    17.63,
    515,
    5800,
    2,
    2,
    designs.twinProp,
    { role: "night fighter" },
  ),
  f(
    "mosquito-f",
    "Mosquito Fighter",
    "de Havilland",
    "United Kingdom",
    1940,
    "World War II",
    "piston",
    13.57,
    16.52,
    668,
    11280,
    2,
    2,
    designs.twinProp,
    { role: "night fighter", variants: ["F Mk II", "NF Mk XIII", "FB Mk VI"] },
  ),
  f(
    "typhoon",
    "Hawker Typhoon",
    "Hawker",
    "United Kingdom",
    1940,
    "World War II",
    "piston",
    9.74,
    12.67,
    663,
    10700,
    1,
    1,
    designs.inline,
    { role: "fighter-bomber" },
  ),
  f(
    "tempest",
    "Hawker Tempest",
    "Hawker",
    "United Kingdom",
    1942,
    "World War II",
    "piston",
    10.26,
    12.49,
    695,
    11100,
    1,
    1,
    designs.inlineElliptical,
    { variants: ["Tempest Mk V", "Tempest Mk II"] },
  ),
  f(
    "firefly",
    "Fairey Firefly",
    "Fairey",
    "United Kingdom",
    1941,
    "World War II",
    "piston",
    11.46,
    13.57,
    509,
    8530,
    1,
    2,
    designs.inline,
    { role: "naval fighter", visual: { naval: true } },
  ),
  f(
    "fulmar",
    "Fairey Fulmar",
    "Fairey",
    "United Kingdom",
    1940,
    "World War II",
    "piston",
    12.24,
    14.14,
    438,
    8300,
    1,
    2,
    designs.inline,
    { role: "naval fighter", visual: { naval: true } },
  ),
  f(
    "hornet",
    "de Havilland Hornet",
    "de Havilland",
    "United Kingdom",
    1944,
    "World War II",
    "piston",
    11.48,
    13.72,
    764,
    12500,
    2,
    1,
    designs.twinProp,
    { role: "escort fighter", variants: ["Hornet F.1/3", "Sea Hornet"] },
  ),
  f(
    "boomerang",
    "CAC Boomerang",
    "Commonwealth Aircraft Corporation",
    "Australia",
    1942,
    "World War II",
    "piston",
    7.77,
    10.97,
    491,
    8800,
    1,
    1,
    designs.radial,
  ),

  // Germany
  f(
    "bf-109",
    "Bf 109",
    "Messerschmitt",
    "Germany",
    1935,
    "World War II",
    "piston",
    8.95,
    9.92,
    640,
    12000,
    1,
    1,
    designs.inline,
    { variants: ["Bf 109E/F/G/K"] },
  ),
  f(
    "bf-110",
    "Bf 110",
    "Messerschmitt",
    "Germany",
    1936,
    "World War II",
    "piston",
    12.07,
    16.25,
    595,
    11000,
    2,
    2,
    designs.twinPropTwinTail,
    { role: "night fighter", variants: ["Bf 110C/F/G"] },
  ),
  f(
    "fw-190",
    "Fw 190",
    "Focke-Wulf",
    "Germany",
    1939,
    "World War II",
    "piston",
    8.95,
    10.51,
    656,
    11410,
    1,
    1,
    designs.radial,
    { variants: ["Fw 190A/F/D"] },
  ),
  f(
    "ta-152",
    "Ta 152",
    "Focke-Wulf",
    "Germany",
    1944,
    "World War II",
    "piston",
    10.82,
    14.44,
    759,
    15100,
    1,
    1,
    designs.inline,
    { role: "interceptor" },
  ),
  f(
    "me-163",
    "Me 163 Komet",
    "Messerschmitt",
    "Germany",
    1941,
    "World War II",
    "rocket",
    5.7,
    9.3,
    1004,
    12100,
    1,
    1,
    designs.rocket,
    { role: "interceptor" },
  ),
  f(
    "me-262",
    "Me 262 Schwalbe",
    "Messerschmitt",
    "Germany",
    1942,
    "World War II",
    "turbojet",
    10.6,
    12.6,
    900,
    11450,
    2,
    1,
    designs.straightTwinJet,
    {
      role: "interceptor",
      visual: { wing: "swept", sweepDeg: 18, wingPods: true },
      variants: ["Me 262 A-1a", "Me 262 B-1a/U1"],
    },
  ),
  f(
    "he-162",
    "He 162 Salamander",
    "Heinkel",
    "Germany",
    1944,
    "World War II",
    "turbojet",
    9.05,
    7.2,
    840,
    12000,
    1,
    1,
    designs.straightJet,
    {
      role: "interceptor",
      visual: { dorsalIntake: true, intake: "side", tail: "twin" },
    },
  ),
  f(
    "he-280",
    "He 280",
    "Heinkel",
    "Germany",
    1940,
    "World War II",
    "turbojet",
    10.4,
    12.2,
    820,
    11500,
    2,
    1,
    designs.straightTwinJet,
    { role: "day fighter", status: "prototype / development" },
  ),
  f(
    "do-335",
    "Do 335 Pfeil",
    "Dornier",
    "Germany",
    1943,
    "World War II",
    "piston",
    13.85,
    13.8,
    763,
    11400,
    2,
    1,
    designs.pushPull,
    { role: "interceptor" },
  ),
  f(
    "he-219",
    "He 219 Uhu",
    "Heinkel",
    "Germany",
    1942,
    "World War II",
    "piston",
    15.55,
    18.5,
    616,
    12700,
    2,
    2,
    designs.twinPropTwinTail,
    { role: "night fighter" },
  ),
  f(
    "ju-88g",
    "Ju 88G Night Fighter",
    "Junkers",
    "Germany",
    1941,
    "World War II",
    "piston",
    15.5,
    20.08,
    580,
    9900,
    2,
    3,
    designs.twinProp,
    { role: "night fighter" },
  ),

  // Soviet Union
  f(
    "i-15",
    "I-15",
    "Polikarpov",
    "Soviet Union",
    1933,
    "World War II",
    "piston",
    6.1,
    9.75,
    367,
    9800,
    1,
    1,
    designs.biplane,
  ),
  f(
    "i-16",
    "I-16",
    "Polikarpov",
    "Soviet Union",
    1933,
    "World War II",
    "piston",
    6.13,
    9.0,
    525,
    9700,
    1,
    1,
    designs.radial,
  ),
  f(
    "mig-3",
    "MiG-3",
    "Mikoyan-Gurevich",
    "Soviet Union",
    1940,
    "World War II",
    "piston",
    8.25,
    10.2,
    640,
    12000,
    1,
    1,
    designs.inline,
    { role: "interceptor" },
  ),
  f(
    "lagg-3",
    "LaGG-3",
    "Lavochkin-Gorbunov-Gudkov",
    "Soviet Union",
    1940,
    "World War II",
    "piston",
    8.81,
    9.8,
    575,
    9700,
    1,
    1,
    designs.inline,
  ),
  f(
    "la-5",
    "La-5",
    "Lavochkin",
    "Soviet Union",
    1942,
    "World War II",
    "piston",
    8.67,
    9.8,
    648,
    11000,
    1,
    1,
    designs.radial,
    { variants: ["La-5", "La-5FN"] },
  ),
  f(
    "la-7",
    "La-7",
    "Lavochkin",
    "Soviet Union",
    1944,
    "World War II",
    "piston",
    8.6,
    9.8,
    661,
    10450,
    1,
    1,
    designs.radial,
  ),
  f(
    "yak-1",
    "Yak-1",
    "Yakovlev",
    "Soviet Union",
    1940,
    "World War II",
    "piston",
    8.48,
    10.0,
    592,
    10000,
    1,
    1,
    designs.inline,
  ),
  f(
    "yak-7",
    "Yak-7",
    "Yakovlev",
    "Soviet Union",
    1940,
    "World War II",
    "piston",
    8.5,
    10.0,
    615,
    10200,
    1,
    1,
    designs.inline,
    { variants: ["Yak-7A/B/D"] },
  ),
  f(
    "yak-3",
    "Yak-3",
    "Yakovlev",
    "Soviet Union",
    1943,
    "World War II",
    "piston",
    8.5,
    9.2,
    655,
    10700,
    1,
    1,
    designs.inline,
  ),
  f(
    "yak-9",
    "Yak-9",
    "Yakovlev",
    "Soviet Union",
    1942,
    "World War II",
    "piston",
    8.5,
    9.74,
    672,
    11100,
    1,
    1,
    designs.inline,
    { variants: ["Yak-9D/T/U/P"] },
  ),

  // Japan
  f(
    "ki-27",
    "Ki-27",
    "Nakajima",
    "Japan",
    1936,
    "World War II",
    "piston",
    7.53,
    11.31,
    470,
    12250,
    1,
    1,
    designs.radial,
  ),
  f(
    "ki-43",
    "Ki-43 Hayabusa",
    "Nakajima",
    "Japan",
    1939,
    "World War II",
    "piston",
    8.92,
    10.84,
    576,
    11200,
    1,
    1,
    designs.radialElliptical,
    { variants: ["Ki-43-I/II/III"] },
  ),
  f(
    "ki-44",
    "Ki-44 Shoki",
    "Nakajima",
    "Japan",
    1940,
    "World War II",
    "piston",
    8.84,
    9.45,
    605,
    11200,
    1,
    1,
    designs.radial,
    { role: "interceptor" },
  ),
  f(
    "ki-45",
    "Ki-45 Toryu",
    "Kawasaki",
    "Japan",
    1939,
    "World War II",
    "piston",
    11.0,
    15.02,
    540,
    10000,
    2,
    2,
    designs.twinProp,
    { role: "night fighter" },
  ),
  f(
    "ki-61",
    "Ki-61 Hien",
    "Kawasaki",
    "Japan",
    1941,
    "World War II",
    "piston",
    8.94,
    12.0,
    580,
    11600,
    1,
    1,
    designs.inline,
  ),
  f(
    "ki-84",
    "Ki-84 Hayate",
    "Nakajima",
    "Japan",
    1943,
    "World War II",
    "piston",
    9.92,
    11.24,
    687,
    10500,
    1,
    1,
    designs.radial,
  ),
  f(
    "ki-100",
    "Ki-100",
    "Kawasaki",
    "Japan",
    1945,
    "World War II",
    "piston",
    8.82,
    12.0,
    580,
    11000,
    1,
    1,
    designs.radial,
  ),
  f(
    "a5m",
    "A5M",
    "Mitsubishi",
    "Japan",
    1935,
    "World War II",
    "piston",
    7.57,
    11.0,
    440,
    9800,
    1,
    1,
    designs.radialElliptical,
    { role: "naval fighter", visual: { naval: true } },
  ),
  f(
    "a6m",
    "A6M Zero",
    "Mitsubishi",
    "Japan",
    1939,
    "World War II",
    "piston",
    9.06,
    12.0,
    565,
    10000,
    1,
    1,
    designs.radialElliptical,
    {
      role: "naval fighter",
      variants: ["A6M2", "A6M3", "A6M5"],
      visual: { naval: true },
    },
  ),
  f(
    "j2m",
    "J2M Raiden",
    "Mitsubishi",
    "Japan",
    1942,
    "World War II",
    "piston",
    9.95,
    10.8,
    596,
    11700,
    1,
    1,
    designs.radial,
    { role: "interceptor" },
  ),
  f(
    "n1k",
    "N1K Shiden",
    "Kawanishi",
    "Japan",
    1942,
    "World War II",
    "piston",
    9.35,
    12.0,
    594,
    12500,
    1,
    1,
    designs.radial,
    { variants: ["N1K1-J", "N1K2-J Shiden-Kai"] },
  ),
  f(
    "j1n",
    "J1N Gekkō",
    "Nakajima",
    "Japan",
    1941,
    "World War II",
    "piston",
    12.18,
    16.98,
    507,
    10530,
    2,
    2,
    designs.twinProp,
    { role: "night fighter" },
  ),
  f(
    "j7w",
    "J7W Shinden",
    "Kyushu",
    "Japan",
    1945,
    "World War II",
    "piston",
    9.66,
    11.11,
    750,
    12000,
    1,
    1,
    designs.pushPull,
    {
      role: "interceptor",
      status: "prototype / development",
      visual: { canards: true, pusher: true },
    },
  ),
  f(
    "kikka",
    "Kikka",
    "Nakajima",
    "Japan",
    1945,
    "World War II",
    "turbojet",
    8.13,
    10.0,
    696,
    12000,
    2,
    1,
    designs.straightTwinJet,
    {
      role: "fighter-bomber",
      status: "prototype / development",
      visual: { wing: "swept", sweepDeg: 14 },
    },
  ),

  // Italy, France, and other combatant nations
  f(
    "cr-42",
    "CR.42 Falco",
    "Fiat",
    "Italy",
    1938,
    "World War II",
    "piston",
    8.25,
    9.7,
    441,
    10190,
    1,
    1,
    designs.biplane,
  ),
  f(
    "g-50",
    "G.50 Freccia",
    "Fiat",
    "Italy",
    1937,
    "World War II",
    "piston",
    7.8,
    10.99,
    470,
    10700,
    1,
    1,
    designs.radial,
  ),
  f(
    "mc-200",
    "C.200 Saetta",
    "Macchi",
    "Italy",
    1937,
    "World War II",
    "piston",
    8.19,
    10.58,
    504,
    8900,
    1,
    1,
    designs.radial,
  ),
  f(
    "mc-202",
    "C.202 Folgore",
    "Macchi",
    "Italy",
    1940,
    "World War II",
    "piston",
    8.85,
    10.58,
    600,
    11500,
    1,
    1,
    designs.inline,
  ),
  f(
    "mc-205",
    "C.205 Veltro",
    "Macchi",
    "Italy",
    1942,
    "World War II",
    "piston",
    8.85,
    10.58,
    640,
    11500,
    1,
    1,
    designs.inline,
  ),
  f(
    "re-2001",
    "Re.2001 Falco II",
    "Reggiane",
    "Italy",
    1940,
    "World War II",
    "piston",
    8.36,
    11.0,
    542,
    11000,
    1,
    1,
    designs.inline,
    { variants: ["Re.2001", "Re.2001 CN"] },
  ),
  f(
    "re-2005",
    "Re.2005 Sagittario",
    "Reggiane",
    "Italy",
    1942,
    "World War II",
    "piston",
    8.73,
    11.0,
    628,
    11500,
    1,
    1,
    designs.inline,
  ),
  f(
    "g-55",
    "G.55 Centauro",
    "Fiat",
    "Italy",
    1942,
    "World War II",
    "piston",
    9.37,
    11.85,
    623,
    12700,
    1,
    1,
    designs.inline,
  ),
  f(
    "ms-406",
    "M.S.406",
    "Morane-Saulnier",
    "France",
    1935,
    "World War II",
    "piston",
    8.17,
    10.62,
    486,
    9850,
    1,
    1,
    designs.inline,
  ),
  f(
    "d-520",
    "D.520",
    "Dewoitine",
    "France",
    1938,
    "World War II",
    "piston",
    8.76,
    10.2,
    560,
    11000,
    1,
    1,
    designs.inline,
  ),
  f(
    "mb-152",
    "MB.152",
    "Bloch",
    "France",
    1938,
    "World War II",
    "piston",
    9.1,
    10.54,
    509,
    10000,
    1,
    1,
    designs.radial,
  ),
  f(
    "c-714",
    "C.714 Cyclone",
    "Caudron-Renault",
    "France",
    1936,
    "World War II",
    "piston",
    8.53,
    8.97,
    487,
    9100,
    1,
    1,
    designs.inline,
  ),
  f(
    "potez-631",
    "Potez 631",
    "Potez",
    "France",
    1937,
    "World War II",
    "piston",
    11.07,
    16.0,
    442,
    9500,
    2,
    3,
    designs.twinPropTwinTail,
    { role: "night fighter" },
  ),
  f(
    "vg-33",
    "Arsenal VG-33",
    "Arsenal de l'Aéronautique",
    "France",
    1939,
    "World War II",
    "piston",
    8.55,
    10.8,
    558,
    11000,
    1,
    1,
    designs.inline,
  ),
  f(
    "pzl-p11",
    "PZL P.11",
    "PZL",
    "Poland",
    1931,
    "World War II",
    "piston",
    7.55,
    10.72,
    390,
    8000,
    1,
    1,
    designs.radial,
    { visual: { wing: "swept", sweepDeg: 8 } },
  ),
  f(
    "pzl-p24",
    "PZL P.24",
    "PZL",
    "Poland",
    1933,
    "World War II",
    "piston",
    7.5,
    10.68,
    430,
    10500,
    1,
    1,
    designs.radial,
    { visual: { wing: "swept", sweepDeg: 8 } },
  ),
  f(
    "fokker-d21",
    "Fokker D.XXI",
    "Fokker",
    "Netherlands",
    1936,
    "World War II",
    "piston",
    8.2,
    11.0,
    460,
    11350,
    1,
    1,
    designs.radial,
  ),
  f(
    "fokker-gi",
    "Fokker G.I",
    "Fokker",
    "Netherlands",
    1937,
    "World War II",
    "piston",
    11.5,
    17.16,
    475,
    10000,
    2,
    2,
    designs.twinBoomProp,
  ),
  f(
    "iar-80",
    "IAR 80",
    "Industria Aeronautică Română",
    "Romania",
    1939,
    "World War II",
    "piston",
    8.97,
    10.52,
    560,
    10500,
    1,
    1,
    designs.radial,
    { variants: ["IAR 80", "IAR 81"] },
  ),
  f(
    "b-534",
    "Avia B-534",
    "Avia",
    "Czechoslovakia",
    1933,
    "World War II",
    "piston",
    8.2,
    9.4,
    405,
    10600,
    1,
    1,
    designs.biplane,
  ),
  f(
    "j-22",
    "FFVS J 22",
    "FFVS",
    "Sweden",
    1942,
    "World War II",
    "piston",
    7.8,
    10.0,
    575,
    9300,
    1,
    1,
    designs.radial,
  ),
  f(
    "j-21",
    "Saab J 21",
    "Saab",
    "Sweden",
    1943,
    "World War II",
    "piston",
    10.45,
    11.6,
    640,
    11000,
    1,
    1,
    designs.twinBoomProp,
    { visual: { canards: false, pusher: true } },
  ),
  f(
    "myrsky",
    "VL Myrsky",
    "Valtion lentokonetehdas",
    "Finland",
    1941,
    "World War II",
    "piston",
    8.35,
    11.0,
    535,
    9500,
    1,
    1,
    designs.radial,
  ),
  f(
    "cw-21",
    "CW-21 Demon",
    "Curtiss-Wright",
    "United States",
    1938,
    "World War II",
    "piston",
    8.29,
    10.66,
    505,
    10600,
    1,
    1,
    designs.inline,
    { role: "interceptor", operators: ["China", "Netherlands East Indies"] },
  ),
  f(
    "ik-3",
    "Rogožarski IK-3",
    "Rogožarski",
    "Yugoslavia",
    1938,
    "World War II",
    "piston",
    8.0,
    10.3,
    527,
    9400,
    1,
    1,
    designs.inline,
  ),
];

const EARLY_JETS: FighterProfile[] = [
  f(
    "meteor",
    "Gloster Meteor",
    "Gloster",
    "United Kingdom",
    1943,
    "World War II",
    "turbojet",
    13.59,
    11.32,
    965,
    13100,
    2,
    1,
    designs.straightTwinJet,
    {
      role: "day fighter",
      variants: ["F.3", "F.4", "F.8", "NF.11/14"],
      summary:
        "The only Allied jet fighter to conduct combat operations during World War II.",
    },
  ),
  f(
    "vampire",
    "de Havilland Vampire",
    "de Havilland",
    "United Kingdom",
    1943,
    "Early jet age",
    "turbojet",
    9.37,
    11.58,
    882,
    13045,
    1,
    1,
    designs.twinBoomJet,
    { role: "day fighter", variants: ["F.1", "FB.5", "Sea Vampire"] },
  ),
  f(
    "venom",
    "de Havilland Venom",
    "de Havilland",
    "United Kingdom",
    1949,
    "Early jet age",
    "turbojet",
    10.06,
    12.7,
    1030,
    15000,
    1,
    1,
    designs.twinBoomJet,
    { role: "fighter-bomber" },
  ),
  f(
    "f-80",
    "F-80 Shooting Star",
    "Lockheed",
    "United States",
    1944,
    "Early jet age",
    "turbojet",
    10.49,
    11.85,
    956,
    14100,
    1,
    1,
    designs.straightJet,
    { role: "day fighter" },
  ),
  f(
    "f-84",
    "F-84 Thunderjet",
    "Republic",
    "United States",
    1946,
    "Early jet age",
    "turbojet",
    11.6,
    11.1,
    1000,
    12350,
    1,
    1,
    designs.straightJet,
    { role: "fighter-bomber", variants: ["F-84B/G", "F-84F Thunderstreak"] },
  ),
  f(
    "f-86",
    "F-86 Sabre",
    "North American",
    "United States",
    1947,
    "Early jet age",
    "turbojet",
    11.43,
    11.31,
    1106,
    15100,
    1,
    1,
    designs.sweptSingle,
    {
      role: "day fighter",
      variants: ["F-86A/E/F/K", "CAC Sabre", "Canadair Sabre"],
      references: ["nmusaf-f86", "smithsonian"],
    },
  ),
  f(
    "f9f-panther",
    "F9F Panther",
    "Grumman",
    "United States",
    1947,
    "Early jet age",
    "turbojet",
    11.84,
    11.58,
    925,
    13400,
    1,
    1,
    designs.straightJet,
    {
      role: "naval fighter",
      variants: ["F9F-2/3/4/5"],
      visual: { naval: true, wing: "tapered" },
    },
  ),
  f(
    "f9f-cougar",
    "F9F Cougar",
    "Grumman",
    "United States",
    1951,
    "Early jet age",
    "turbojet",
    12.85,
    10.52,
    1050,
    15200,
    1,
    1,
    designs.sweptSingleSide,
    { role: "naval fighter", variants: ["F9F-6/7/8"], visual: { naval: true } },
  ),
  f(
    "f2h",
    "F2H Banshee",
    "McDonnell",
    "United States",
    1947,
    "Early jet age",
    "turbojet",
    14.68,
    12.73,
    943,
    14200,
    2,
    1,
    designs.straightTwinJet,
    {
      role: "naval fighter",
      variants: ["F2H-2", "F2H-3/4"],
      visual: { naval: true },
    },
  ),
  f(
    "f-94",
    "F-94 Starfire",
    "Lockheed",
    "United States",
    1949,
    "Early jet age",
    "turbojet",
    13.56,
    11.89,
    1030,
    15670,
    1,
    2,
    designs.straightJet,
    { role: "interceptor" },
  ),
  f(
    "mig-9",
    "MiG-9",
    "Mikoyan-Gurevich",
    "Soviet Union",
    1946,
    "Early jet age",
    "turbojet",
    9.75,
    10.0,
    910,
    13000,
    2,
    1,
    designs.straightJet,
  ),
  f(
    "mig-15",
    "MiG-15",
    "Mikoyan-Gurevich",
    "Soviet Union",
    1947,
    "Early jet age",
    "turbojet",
    10.1,
    10.08,
    1076,
    15500,
    1,
    1,
    designs.sweptSingle,
    { role: "day fighter", variants: ["MiG-15", "MiG-15bis"] },
  ),
  f(
    "mig-17",
    "MiG-17",
    "Mikoyan-Gurevich",
    "Soviet Union",
    1950,
    "Early jet age",
    "turbojet",
    11.26,
    9.63,
    1145,
    16600,
    1,
    1,
    designs.sweptSingle,
    { role: "day fighter" },
  ),
  f(
    "la-15",
    "La-15",
    "Lavochkin",
    "Soviet Union",
    1948,
    "Early jet age",
    "turbojet",
    9.56,
    8.83,
    1026,
    13000,
    1,
    1,
    designs.sweptSingle,
  ),
  f(
    "yak-15",
    "Yak-15",
    "Yakovlev",
    "Soviet Union",
    1946,
    "Early jet age",
    "turbojet",
    8.7,
    9.2,
    786,
    13350,
    1,
    1,
    designs.straightJet,
    { role: "day fighter" },
  ),
  f(
    "yak-23",
    "Yak-23",
    "Yakovlev",
    "Soviet Union",
    1947,
    "Early jet age",
    "turbojet",
    8.12,
    8.73,
    923,
    14800,
    1,
    1,
    designs.straightJet,
    { role: "day fighter" },
  ),
  f(
    "ouragan",
    "Dassault Ouragan",
    "Dassault",
    "France",
    1949,
    "Early jet age",
    "turbojet",
    10.73,
    13.16,
    940,
    13000,
    1,
    1,
    designs.straightJet,
    { role: "fighter-bomber" },
  ),
  f(
    "mystere-iv",
    "Dassault Mystère IV",
    "Dassault",
    "France",
    1952,
    "Early jet age",
    "turbojet",
    12.89,
    11.12,
    1110,
    15000,
    1,
    1,
    designs.sweptSingle,
    { role: "fighter-bomber" },
  ),
  f(
    "super-mystere",
    "Super Mystère B2",
    "Dassault",
    "France",
    1955,
    "Early jet age",
    "turbojet",
    14.13,
    10.51,
    1250,
    17000,
    1,
    1,
    designs.sweptSingleSide,
    { role: "fighter-bomber" },
  ),
  f(
    "j-29",
    "Saab J 29 Tunnan",
    "Saab",
    "Sweden",
    1948,
    "Early jet age",
    "turbojet",
    10.23,
    11.0,
    1060,
    15500,
    1,
    1,
    designs.sweptSingle,
    { role: "day fighter" },
  ),
  f(
    "cf-100",
    "CF-100 Canuck",
    "Avro Canada",
    "Canada",
    1950,
    "Early jet age",
    "turbojet",
    16.51,
    17.43,
    888,
    13700,
    2,
    2,
    designs.straightTwinJet,
    { role: "interceptor" },
  ),
  f(
    "pulqui-ii",
    "IAe 33 Pulqui II",
    "FMA",
    "Argentina",
    1950,
    "Early jet age",
    "turbojet",
    11.68,
    10.6,
    1080,
    15000,
    1,
    1,
    designs.sweptSingle,
    { status: "prototype / development", role: "day fighter" },
  ),
];

const COLD_WAR: FighterProfile[] = [
  // United States
  f(
    "f-89",
    "F-89 Scorpion",
    "Northrop",
    "United States",
    1948,
    "Cold War",
    "turbojet",
    16.4,
    18.2,
    1022,
    15000,
    2,
    2,
    designs.straightTwinJet,
    { role: "interceptor" },
  ),
  f(
    "f-100",
    "F-100 Super Sabre",
    "North American",
    "United States",
    1953,
    "Cold War",
    "turbojet",
    15.2,
    11.81,
    1390,
    15000,
    1,
    1,
    designs.sweptSingleSide,
    { role: "fighter-bomber" },
  ),
  f(
    "f-101",
    "F-101 Voodoo",
    "McDonnell",
    "United States",
    1954,
    "Cold War",
    "turbojet",
    20.55,
    12.09,
    1825,
    17800,
    2,
    2,
    designs.sweptTwin,
    { role: "interceptor" },
  ),
  f(
    "f-102",
    "F-102 Delta Dagger",
    "Convair",
    "United States",
    1953,
    "Cold War",
    "turbojet",
    20.83,
    11.62,
    1304,
    16500,
    1,
    1,
    designs.delta,
    { role: "interceptor" },
  ),
  f(
    "f-104",
    "F-104 Starfighter",
    "Lockheed",
    "United States",
    1954,
    "Cold War",
    "turbojet",
    16.66,
    6.63,
    2137,
    15200,
    1,
    1,
    designs.sweptSingleSide,
    {
      role: "interceptor",
      visual: { wing: "straight", sweepDeg: 6 },
      variants: ["F-104A/G/S", "CF-104", "F-104J"],
    },
  ),
  f(
    "f-105",
    "F-105 Thunderchief",
    "Republic",
    "United States",
    1955,
    "Cold War",
    "turbojet",
    19.63,
    10.65,
    2208,
    14790,
    1,
    1,
    designs.sweptSingleSide,
    { role: "fighter-bomber", variants: ["F-105B/D/F/G"] },
  ),
  f(
    "f-106",
    "F-106 Delta Dart",
    "Convair",
    "United States",
    1956,
    "Cold War",
    "turbojet",
    21.56,
    11.67,
    2455,
    17400,
    1,
    1,
    designs.delta,
    { role: "interceptor" },
  ),
  f(
    "f-5",
    "F-5 Freedom Fighter / Tiger II",
    "Northrop",
    "United States",
    1959,
    "Cold War",
    "turbojet",
    14.45,
    8.13,
    1700,
    15790,
    2,
    1,
    designs.sweptTwin,
    {
      role: "light fighter",
      variants: ["F-5A/B", "F-5E/F", "F-20 Tigershark"],
    },
  ),
  f(
    "f-8",
    "F-8 Crusader",
    "Vought",
    "United States",
    1955,
    "Cold War",
    "turbojet",
    16.53,
    10.87,
    1975,
    18000,
    1,
    1,
    designs.sweptSingleSide,
    { role: "naval fighter", visual: { naval: true } },
  ),
  f(
    "f-11",
    "F11F Tiger",
    "Grumman",
    "United States",
    1954,
    "Cold War",
    "turbojet",
    13.98,
    9.64,
    1170,
    14900,
    1,
    1,
    designs.sweptSingleSide,
    { role: "naval fighter", visual: { naval: true } },
  ),
  f(
    "f3h",
    "F3H Demon",
    "McDonnell",
    "United States",
    1951,
    "Cold War",
    "turbojet",
    17.98,
    10.77,
    1152,
    13000,
    1,
    1,
    designs.sweptSingleSide,
    { role: "naval fighter", visual: { naval: true } },
  ),
  f(
    "f-4",
    "F-4 Phantom II",
    "McDonnell Douglas",
    "United States",
    1958,
    "Cold War",
    "turbojet",
    19.2,
    11.71,
    2370,
    18300,
    2,
    2,
    designs.sweptTwin,
    {
      role: "multirole",
      variants: ["F-4B/C/D/E/J/K/M", "F-4F", "F-4EJ"],
      visual: { naval: true },
    },
  ),
  f(
    "f-14",
    "F-14 Tomcat",
    "Grumman",
    "United States",
    1970,
    "Cold War",
    "turbofan",
    19.13,
    19.55,
    2485,
    17070,
    2,
    2,
    designs.variable,
    { role: "naval fighter", variants: ["F-14A/B/D"], visual: { naval: true } },
  ),
  f(
    "f-15",
    "F-15 Eagle",
    "McDonnell Douglas",
    "United States",
    1972,
    "Cold War",
    "turbofan",
    19.43,
    13.05,
    2655,
    19800,
    2,
    1,
    designs.sweptTwin,
    {
      role: "air superiority",
      variants: ["F-15A/C", "F-15E", "F-15J", "F-15I/K/SA/QA"],
    },
  ),
  f(
    "f-16",
    "F-16 Fighting Falcon",
    "General Dynamics",
    "United States",
    1974,
    "Cold War",
    "turbofan",
    15.06,
    9.96,
    2120,
    15240,
    1,
    1,
    designs.croppedDelta,
    {
      role: "multirole",
      variants: ["F-16A/B", "F-16C/D", "F-16V / Block 70/72"],
    },
  ),
  f(
    "fa-18",
    "F/A-18 Hornet",
    "McDonnell Douglas",
    "United States",
    1978,
    "Cold War",
    "turbofan",
    17.07,
    11.43,
    1915,
    15200,
    2,
    1,
    designs.sweptTwin,
    {
      role: "naval fighter",
      variants: ["F/A-18A/B/C/D"],
      visual: { naval: true },
    },
  ),

  // Soviet Union / Russia
  f(
    "mig-19",
    "MiG-19",
    "Mikoyan-Gurevich",
    "Soviet Union",
    1952,
    "Cold War",
    "turbojet",
    12.54,
    9.0,
    1455,
    17500,
    2,
    1,
    designs.sweptTwin,
    { role: "interceptor" },
  ),
  f(
    "mig-21",
    "MiG-21",
    "Mikoyan-Gurevich",
    "Soviet Union",
    1955,
    "Cold War",
    "turbojet",
    14.7,
    7.15,
    2175,
    17500,
    1,
    1,
    designs.delta,
    { role: "interceptor", variants: ["MiG-21F/PF/MF/bis", "Chengdu J-7"] },
  ),
  f(
    "mig-23",
    "MiG-23",
    "Mikoyan-Gurevich",
    "Soviet Union",
    1967,
    "Cold War",
    "turbojet",
    16.7,
    13.97,
    2500,
    18500,
    1,
    1,
    designs.variable,
    { role: "interceptor", variants: ["MiG-23M/ML/MLD"] },
  ),
  f(
    "mig-25",
    "MiG-25 Foxbat",
    "Mikoyan-Gurevich",
    "Soviet Union",
    1964,
    "Cold War",
    "turbojet",
    23.82,
    14.01,
    3000,
    20700,
    2,
    1,
    designs.sweptTwin,
    { role: "interceptor" },
  ),
  f(
    "mig-29",
    "MiG-29 Fulcrum",
    "Mikoyan",
    "Soviet Union",
    1977,
    "Cold War",
    "turbofan",
    17.32,
    11.36,
    2450,
    18000,
    2,
    1,
    designs.sweptTwin,
    { role: "air superiority", variants: ["MiG-29A/S/M/K", "MiG-29M"] },
  ),
  f(
    "mig-31",
    "MiG-31 Foxhound",
    "Mikoyan",
    "Soviet Union",
    1975,
    "Cold War",
    "turbofan",
    22.62,
    13.46,
    3000,
    20600,
    2,
    2,
    designs.sweptTwin,
    { role: "interceptor", status: "operational" },
  ),
  f(
    "su-15",
    "Su-15 Flagon",
    "Sukhoi",
    "Soviet Union",
    1962,
    "Cold War",
    "turbojet",
    19.56,
    9.34,
    2230,
    18100,
    2,
    1,
    designs.delta,
    { role: "interceptor", visual: { wing: "cropped-delta" } },
  ),
  f(
    "su-9",
    "Su-9 Fishpot",
    "Sukhoi",
    "Soviet Union",
    1956,
    "Cold War",
    "turbojet",
    17.37,
    8.54,
    2230,
    20000,
    1,
    1,
    designs.delta,
    { role: "interceptor" },
  ),
  f(
    "su-11",
    "Su-11 Fishpot-C",
    "Sukhoi",
    "Soviet Union",
    1958,
    "Cold War",
    "turbojet",
    18.29,
    8.43,
    2340,
    18000,
    1,
    1,
    designs.delta,
    { role: "interceptor" },
  ),
  f(
    "yak-25",
    "Yak-25 Flashlight",
    "Yakovlev",
    "Soviet Union",
    1952,
    "Cold War",
    "turbojet",
    15.67,
    10.94,
    1090,
    15200,
    2,
    2,
    designs.sweptTwin,
    { role: "interceptor", visual: { wingPods: true } },
  ),
  f(
    "su-27",
    "Su-27 Flanker",
    "Sukhoi",
    "Soviet Union",
    1977,
    "Cold War",
    "turbofan",
    21.94,
    14.7,
    2500,
    19000,
    2,
    1,
    designs.sweptTwin,
    {
      role: "air superiority",
      status: "operational",
      variants: ["Su-27S/SM", "Su-30", "Su-33", "Su-35"],
    },
  ),
  f(
    "yak-38",
    "Yak-38",
    "Yakovlev",
    "Soviet Union",
    1971,
    "Cold War",
    "turbojet",
    16.37,
    7.32,
    1280,
    12000,
    3,
    1,
    designs.vtol,
    { role: "naval fighter", visual: { naval: true } },
  ),

  // Europe and other national programs
  f(
    "hunter",
    "Hawker Hunter",
    "Hawker",
    "United Kingdom",
    1951,
    "Cold War",
    "turbojet",
    14.0,
    10.26,
    1150,
    15240,
    1,
    1,
    designs.sweptSingleSide,
    { role: "fighter-bomber" },
  ),
  f(
    "javelin",
    "Gloster Javelin",
    "Gloster",
    "United Kingdom",
    1951,
    "Cold War",
    "turbojet",
    17.15,
    15.85,
    1140,
    15865,
    2,
    2,
    designs.delta,
    { role: "interceptor", visual: { tail: "single" } },
  ),
  f(
    "sea-hawk",
    "Hawker Sea Hawk",
    "Hawker",
    "United Kingdom",
    1947,
    "Cold War",
    "turbojet",
    12.09,
    11.89,
    965,
    13560,
    1,
    1,
    designs.straightJet,
    { role: "naval fighter", visual: { naval: true, intake: "wing-root" } },
  ),
  f(
    "gnat",
    "Folland Gnat",
    "Folland",
    "United Kingdom",
    1955,
    "Cold War",
    "turbojet",
    8.74,
    6.73,
    1120,
    14630,
    1,
    1,
    designs.sweptSingleSide,
    { role: "light fighter", variants: ["Gnat F.1", "HAL Ajeet"] },
  ),
  f(
    "lightning",
    "English Electric Lightning",
    "English Electric",
    "United Kingdom",
    1954,
    "Cold War",
    "turbojet",
    16.84,
    10.62,
    2415,
    18300,
    2,
    1,
    designs.delta,
    { role: "interceptor", visual: { wing: "swept", sweepDeg: 60 } },
  ),
  f(
    "sea-vixen",
    "de Havilland Sea Vixen",
    "de Havilland",
    "United Kingdom",
    1951,
    "Cold War",
    "turbojet",
    16.94,
    15.54,
    1110,
    15000,
    2,
    2,
    designs.twinBoomJet,
    { role: "naval fighter", visual: { naval: true } },
  ),
  f(
    "harrier",
    "Harrier / Sea Harrier",
    "Hawker Siddeley",
    "United Kingdom",
    1967,
    "Cold War",
    "turbofan",
    14.27,
    7.7,
    1185,
    15600,
    1,
    1,
    designs.vtol,
    {
      role: "multirole",
      variants: ["Harrier GR.1/3", "Sea Harrier FRS.1/FA.2", "AV-8A/B"],
    },
  ),
  f(
    "tornado-adv",
    "Tornado ADV",
    "Panavia",
    "European consortium",
    1979,
    "Cold War",
    "turbofan",
    18.68,
    13.91,
    2400,
    15240,
    2,
    2,
    designs.variable,
    { role: "interceptor", variants: ["F.2", "F.3"] },
  ),
  f(
    "mirage-iii",
    "Mirage III / 5",
    "Dassault",
    "France",
    1956,
    "Cold War",
    "turbojet",
    15.03,
    8.22,
    2350,
    17000,
    1,
    1,
    designs.delta,
    { role: "interceptor", variants: ["Mirage III C/E", "Mirage 5", "Nesher"] },
  ),
  f(
    "mirage-f1",
    "Mirage F1",
    "Dassault",
    "France",
    1966,
    "Cold War",
    "turbojet",
    15.3,
    8.44,
    2335,
    20000,
    1,
    1,
    designs.sweptSingleSide,
    { role: "interceptor" },
  ),
  f(
    "etendard-iv",
    "Étendard IV",
    "Dassault",
    "France",
    1956,
    "Cold War",
    "turbojet",
    14.35,
    9.6,
    1099,
    15000,
    1,
    1,
    designs.sweptSingleSide,
    { role: "naval fighter", visual: { naval: true } },
  ),
  f(
    "mirage-2000",
    "Mirage 2000",
    "Dassault",
    "France",
    1978,
    "Cold War",
    "turbofan",
    14.36,
    9.13,
    2336,
    17060,
    1,
    1,
    designs.delta,
    {
      role: "multirole",
      status: "operational",
      variants: ["2000C", "2000-5", "2000D", "2000I"],
    },
  ),
  f(
    "j-35",
    "Saab J 35 Draken",
    "Saab",
    "Sweden",
    1955,
    "Cold War",
    "turbojet",
    15.35,
    9.42,
    2120,
    20000,
    1,
    1,
    designs.delta,
    { role: "interceptor" },
  ),
  f(
    "j-32",
    "Saab J 32B Lansen",
    "Saab",
    "Sweden",
    1952,
    "Cold War",
    "turbojet",
    14.94,
    13.0,
    1200,
    15000,
    1,
    2,
    designs.sweptSingleSide,
    { role: "interceptor", variants: ["J 32B", "A 32A", "S 32C"] },
  ),
  f(
    "ja-37",
    "Saab 37 Viggen",
    "Saab",
    "Sweden",
    1967,
    "Cold War",
    "turbofan",
    16.4,
    10.6,
    2231,
    18000,
    1,
    1,
    designs.canardDelta,
    { role: "interceptor", variants: ["AJ 37", "JA 37"] },
  ),
  f(
    "j-8",
    "Shenyang J-8",
    "Shenyang",
    "China",
    1969,
    "Cold War",
    "turbojet",
    21.59,
    9.34,
    2339,
    20500,
    2,
    1,
    designs.delta,
    { role: "interceptor", variants: ["J-8I", "J-8II"] },
  ),
  f(
    "j-6",
    "Shenyang J-6",
    "Shenyang",
    "China",
    1958,
    "Cold War",
    "turbojet",
    12.54,
    9.0,
    1450,
    17900,
    2,
    1,
    designs.sweptTwin,
    { role: "day fighter", variants: ["J-6A/B/C", "F-6 export"] },
  ),
  f(
    "j-7",
    "Chengdu J-7",
    "Chengdu",
    "China",
    1966,
    "Cold War",
    "turbojet",
    14.88,
    8.32,
    2175,
    17500,
    1,
    1,
    designs.delta,
    { role: "light fighter", variants: ["J-7I/II/III/E/G", "F-7 export"] },
  ),
  f(
    "hf-24",
    "HF-24 Marut",
    "Hindustan Aeronautics",
    "India",
    1961,
    "Cold War",
    "turbojet",
    15.87,
    9.0,
    1112,
    13750,
    2,
    1,
    designs.sweptTwin,
    { role: "fighter-bomber" },
  ),
  f(
    "g-91",
    "Fiat G.91",
    "Fiat Aviazione",
    "Italy",
    1956,
    "Cold War",
    "turbojet",
    10.3,
    8.56,
    1075,
    13100,
    1,
    1,
    designs.sweptSingleSide,
    { role: "light fighter", variants: ["G.91R/T", "G.91Y"] },
  ),
  f(
    "kfir",
    "IAI Kfir",
    "Israel Aerospace Industries",
    "Israel",
    1973,
    "Cold War",
    "turbojet",
    15.65,
    8.22,
    2440,
    17700,
    1,
    1,
    designs.canardDelta,
    { role: "multirole", variants: ["Kfir C.2/C.7/C.10"] },
  ),
  f(
    "f-1",
    "Mitsubishi F-1",
    "Mitsubishi",
    "Japan",
    1975,
    "Cold War",
    "turbofan",
    17.85,
    7.88,
    1700,
    15240,
    2,
    1,
    designs.sweptTwin,
    { role: "fighter-bomber" },
  ),
  f(
    "f-ck-1",
    "F-CK-1 Ching-kuo",
    "AIDC",
    "Taiwan",
    1989,
    "Cold War",
    "turbofan",
    14.48,
    9.46,
    2220,
    16760,
    2,
    1,
    designs.sweptTwin,
    { role: "multirole", status: "operational" },
  ),
  f(
    "cheetah",
    "Atlas Cheetah",
    "Atlas Aircraft",
    "South Africa",
    1986,
    "Cold War",
    "turbojet",
    15.65,
    8.22,
    2350,
    17000,
    1,
    1,
    designs.canardDelta,
    { role: "multirole", status: "limited service" },
  ),
  f(
    "cf-105",
    "CF-105 Arrow",
    "Avro Canada",
    "Canada",
    1958,
    "Cold War",
    "turbojet",
    23.71,
    15.24,
    2104,
    16150,
    2,
    2,
    designs.delta,
    { role: "interceptor", status: "prototype / development" },
  ),
  f(
    "yak-141",
    "Yak-141 Freestyle",
    "Yakovlev",
    "Soviet Union",
    1987,
    "Cold War",
    "turbofan",
    18.36,
    10.1,
    1800,
    15000,
    3,
    1,
    designs.vtol,
    {
      role: "naval fighter",
      status: "prototype / development",
      visual: { naval: true },
    },
  ),
];

const MODERN: FighterProfile[] = [
  f(
    "f-15ex",
    "F-15EX Eagle II",
    "Boeing",
    "United States",
    2021,
    "Modern",
    "turbofan",
    19.4,
    13.0,
    3060,
    15240,
    2,
    2,
    designs.sweptTwin,
    {
      role: "air superiority",
      variants: ["F-15EX", "Advanced Eagle family"],
      references: ["boeing-fighters"],
    },
  ),
  f(
    "fa-18ef",
    "F/A-18E/F Super Hornet",
    "Boeing",
    "United States",
    1995,
    "Modern",
    "turbofan",
    18.31,
    13.62,
    1915,
    15240,
    2,
    1,
    designs.sweptTwin,
    {
      role: "naval fighter",
      variants: ["F/A-18E", "F/A-18F", "EA-18G airframe"],
      visual: { naval: true },
      references: ["boeing-fighters"],
    },
  ),
  f(
    "f-22",
    "F-22 Raptor",
    "Lockheed Martin",
    "United States",
    1997,
    "Modern",
    "turbofan",
    18.9,
    13.6,
    2410,
    15000,
    2,
    1,
    designs.stealthTwin,
    {
      role: "air superiority",
      variants: ["F-22A"],
      summary:
        "Aircraft-specific F-22A geometry uses the USAF's public dimensions and visible external features; classified signature and sensor details are not inferred.",
      references: ["usaf-f22"],
    },
  ),
  f(
    "f-35",
    "F-35 Lightning II",
    "Lockheed Martin",
    "United States",
    2000,
    "Modern",
    "turbofan",
    15.7,
    10.7,
    1975,
    15240,
    1,
    1,
    designs.stealthSingle,
    {
      variants: ["F-35A CTOL (modeled)", "F-35B STOVL", "F-35C carrier"],
      operators: [
        "United States",
        "United Kingdom",
        "Italy",
        "Netherlands",
        "Australia",
        "Norway",
        "Denmark",
        "Israel",
        "Japan",
        "South Korea",
        "Belgium",
        "Poland",
        "Finland",
        "Switzerland",
        "Germany",
        "Canada",
      ],
      summary:
        "The displayed aircraft-specific geometry and dimensions represent the conventional-takeoff F-35A; the B and C remain related family variants.",
      references: ["usaf-f35a", "f35-program"],
    },
  ),
  f(
    "mig-35",
    "Mikoyan MiG-35",
    "Mikoyan / United Aircraft Corporation",
    "Russia",
    2016,
    "Modern",
    "turbofan",
    17.3,
    12,
    2100,
    16000,
    2,
    1,
    designs.sweptTwin,
    {
      role: "multirole",
      status: "limited service",
      variants: ["MiG-35", "MiG-35D"],
      summary:
        "UAC describes the MiG-35 as its newest flown MiG fighter. This aircraft-specific display uses its published dimensions and visible production configuration; the speculative MiG-41 is not treated as a real aircraft.",
      references: ["uac-mig35", "roe-mig35"],
    },
  ),
  f(
    "su-30",
    "Su-30 Flanker-C",
    "Sukhoi",
    "Russia",
    1989,
    "Modern",
    "turbofan",
    21.94,
    14.7,
    2120,
    17300,
    2,
    2,
    designs.sweptTwin,
    {
      role: "multirole",
      variants: ["Su-30MKI", "Su-30MKA", "Su-30MKM", "Su-30SM"],
    },
  ),
  f(
    "su-33",
    "Su-33 Flanker-D",
    "Sukhoi",
    "Russia",
    1987,
    "Modern",
    "turbofan",
    21.19,
    14.7,
    2300,
    17000,
    2,
    1,
    designs.sweptTwin,
    {
      role: "naval fighter",
      status: "limited service",
      visual: { naval: true },
    },
  ),
  f(
    "su-35",
    "Su-35S Flanker-E",
    "Sukhoi",
    "Russia",
    2008,
    "Modern",
    "turbofan",
    21.9,
    15.3,
    2400,
    18000,
    2,
    1,
    designs.sweptTwin,
    { role: "air superiority" },
  ),
  f(
    "su-57",
    "Su-57 Felon",
    "Sukhoi",
    "Russia",
    2010,
    "Modern",
    "turbofan",
    20.1,
    14.1,
    2135,
    20000,
    2,
    1,
    designs.stealthTwin,
    { role: "air superiority", status: "limited service" },
  ),
  f(
    "j-10",
    "Chengdu J-10",
    "Chengdu Aircraft Industry Group",
    "China",
    1998,
    "Modern",
    "turbofan",
    16.9,
    9.75,
    2200,
    18000,
    1,
    1,
    designs.canardDelta,
    { variants: ["J-10A/B/C", "J-10CE"] },
  ),
  f(
    "j-11",
    "Shenyang J-11",
    "Shenyang Aircraft Corporation",
    "China",
    1998,
    "Modern",
    "turbofan",
    21.9,
    14.7,
    2500,
    19000,
    2,
    1,
    designs.sweptTwin,
    { role: "air superiority", variants: ["J-11A/B/BG", "J-16 derivative"] },
  ),
  f(
    "j-15",
    "Shenyang J-15",
    "Shenyang Aircraft Corporation",
    "China",
    2009,
    "Modern",
    "turbofan",
    21.9,
    14.7,
    2100,
    20000,
    2,
    1,
    designs.sweptTwin,
    { role: "naval fighter", visual: { naval: true } },
  ),
  f(
    "j-16",
    "Shenyang J-16",
    "Shenyang Aircraft Corporation",
    "China",
    2011,
    "Modern",
    "turbofan",
    21.9,
    14.7,
    2120,
    17300,
    2,
    2,
    designs.sweptTwin,
    { role: "multirole" },
  ),
  f(
    "j-20",
    "Chengdu J-20",
    "Chengdu Aircraft Industry Group",
    "China",
    2011,
    "Modern",
    "turbofan",
    20.4,
    13.5,
    2100,
    20000,
    2,
    1,
    designs.stealthTwin,
    {
      role: "air superiority",
      visual: { canards: true, horizontalTail: false },
      variants: ["J-20", "J-20A", "J-20S twin-seat family"],
      summary:
        "The aircraft-specific display is a public-view production J-20 schematic using representative published dimensions; internal geometry and classified performance are intentionally not inferred.",
      references: ["china-mod-j20"],
    },
  ),
  f(
    "j-35a",
    "Shenyang J-35A",
    "Shenyang Aircraft Corporation",
    "China",
    2012,
    "Modern",
    "turbofan",
    17.3,
    11.5,
    2200,
    16000,
    2,
    1,
    designs.stealthTwin,
    {
      role: "air superiority",
      status: "prototype / development",
      variants: ["FC-31 demonstrator", "J-35 naval family", "J-35A"],
    },
  ),
  f(
    "rafale",
    "Dassault Rafale",
    "Dassault Aviation",
    "France",
    1986,
    "Modern",
    "turbofan",
    15.3,
    10.9,
    1912,
    15240,
    2,
    1,
    designs.canardDelta,
    {
      variants: ["Rafale C/B/M", "F3-R", "F4"],
      operators: [
        "France",
        "Egypt",
        "Qatar",
        "India",
        "Greece",
        "Croatia",
        "United Arab Emirates",
        "Indonesia",
        "Serbia",
      ],
      references: ["dassault"],
    },
  ),
  f(
    "eurofighter-typhoon",
    "Eurofighter Typhoon",
    "Eurofighter consortium",
    "European consortium",
    1994,
    "Modern",
    "turbofan",
    15.96,
    10.95,
    2495,
    16760,
    2,
    1,
    designs.canardDelta,
    {
      role: "air superiority",
      operators: [
        "United Kingdom",
        "Germany",
        "Italy",
        "Spain",
        "Austria",
        "Saudi Arabia",
        "Oman",
        "Kuwait",
        "Qatar",
      ],
      references: ["eurofighter"],
    },
  ),
  f(
    "gripen-c",
    "Saab JAS 39 Gripen C/D",
    "Saab",
    "Sweden",
    1988,
    "Modern",
    "turbofan",
    14.9,
    8.4,
    2470,
    15240,
    1,
    1,
    designs.canardDelta,
    {
      role: "light fighter",
      variants: ["Gripen C", "Gripen D"],
      operators: [
        "Sweden",
        "Czech Republic",
        "Hungary",
        "South Africa",
        "Thailand",
      ],
      references: ["saab"],
    },
  ),
  f(
    "gripen-e",
    "Saab Gripen E/F",
    "Saab",
    "Sweden",
    2008,
    "Modern",
    "turbofan",
    15.2,
    8.6,
    2470,
    16000,
    1,
    1,
    designs.canardDelta,
    {
      role: "multirole",
      variants: ["Gripen E", "Gripen F"],
      operators: ["Sweden", "Brazil"],
      references: ["saab"],
    },
  ),
  f(
    "tejas",
    "HAL Tejas",
    "Hindustan Aeronautics",
    "India",
    2001,
    "Modern",
    "turbofan",
    13.2,
    8.2,
    1975,
    15200,
    1,
    1,
    designs.delta,
    {
      role: "light fighter",
      variants: ["Tejas Mk 1", "Mk 1A", "naval demonstrator"],
      references: ["hal"],
    },
  ),
  f(
    "jf-17",
    "JF-17 Thunder",
    "PAC / Chengdu",
    "Pakistan / China",
    2003,
    "Modern",
    "turbofan",
    14.93,
    9.45,
    1910,
    16900,
    1,
    1,
    designs.croppedDelta,
    {
      role: "light fighter",
      variants: ["Block I/II/III"],
      operators: ["Pakistan", "Myanmar", "Nigeria", "Azerbaijan"],
    },
  ),
  f(
    "f-2",
    "Mitsubishi F-2",
    "Mitsubishi / Lockheed Martin",
    "Japan",
    1995,
    "Modern",
    "turbofan",
    15.52,
    11.13,
    2120,
    18000,
    1,
    1,
    designs.croppedDelta,
    { variants: ["F-2A", "F-2B"] },
  ),
  f(
    "fa-50",
    "FA-50 Fighting Eagle",
    "Korea Aerospace Industries",
    "South Korea",
    2002,
    "Modern",
    "turbofan",
    13.14,
    9.45,
    1837,
    14630,
    1,
    2,
    designs.sweptSingleSide,
    {
      role: "light fighter",
      operators: [
        "South Korea",
        "Indonesia",
        "Philippines",
        "Iraq",
        "Thailand",
        "Poland",
        "Malaysia",
      ],
    },
  ),
  f(
    "kf-21",
    "KF-21 Boramae",
    "Korea Aerospace Industries",
    "South Korea",
    2022,
    "Modern",
    "turbofan",
    16.9,
    11.2,
    2200,
    15240,
    2,
    1,
    designs.stealthTwin,
    {
      role: "air superiority",
      status: "prototype / development",
      operators: ["South Korea", "Indonesia"],
    },
  ),
  f(
    "lavi",
    "IAI Lavi",
    "Israel Aerospace Industries",
    "Israel",
    1986,
    "Modern",
    "turbofan",
    14.57,
    8.78,
    1965,
    15240,
    1,
    1,
    designs.canardDelta,
    { role: "multirole", status: "prototype / development" },
  ),
  f(
    "kowsar",
    "HESA Kowsar",
    "HESA",
    "Iran",
    2018,
    "Modern",
    "turbojet",
    14.4,
    8.1,
    1700,
    15700,
    2,
    1,
    designs.sweptTwin,
    { role: "light fighter", status: "limited service" },
  ),
  f(
    "kaan",
    "TAI KAAN",
    "Turkish Aerospace Industries",
    "Turkey",
    2023,
    "Modern",
    "turbofan",
    21.0,
    14.0,
    2200,
    16760,
    2,
    1,
    designs.stealthTwin,
    { role: "air superiority", status: "prototype / development" },
  ),
  f(
    "x-29",
    "Grumman X-29",
    "Grumman",
    "United States",
    1984,
    "Modern",
    "turbofan",
    14.66,
    8.29,
    1770,
    16800,
    1,
    1,
    designs.forwardSwept,
    {
      role: "light fighter",
      status: "prototype / development",
      visual: { canards: true, horizontalTail: false },
      summary:
        "Experimental forward-swept-wing research aircraft included for its influential fighter configuration.",
    },
  ),
  f(
    "f-117",
    "F-117 Nighthawk",
    "Lockheed",
    "United States",
    1981,
    "Modern",
    "turbofan",
    20.08,
    13.2,
    993,
    13700,
    2,
    1,
    designs.facetedVtail,
    {
      role: "fighter-bomber",
      status: "limited service",
      summary:
        "Faceted stealth attack aircraft retained because its fighter designation and silhouette are aviation icons.",
    },
  ),
];

export const FIGHTER_CATALOG: readonly FighterProfile[] = [
  ...WWII,
  ...EARLY_JETS,
  ...COLD_WAR,
  ...MODERN,
].sort((a, b) => a.firstFlight - b.firstFlight || a.name.localeCompare(b.name));

export const FIGHTER_ERAS: readonly FighterEra[] = [
  "World War II",
  "Early jet age",
  "Cold War",
  "Modern",
];

export function fighterById(id: string): FighterProfile | undefined {
  return FIGHTER_CATALOG.find((fighter) => fighter.id === id);
}

export function fighterCatalogStats(): {
  airframes: number;
  nations: number;
  variants: number;
  wwii: number;
  jets: number;
} {
  return {
    airframes: FIGHTER_CATALOG.length,
    nations: new Set(FIGHTER_CATALOG.map((fighter) => fighter.designNation))
      .size,
    variants: FIGHTER_CATALOG.reduce(
      (total, fighter) => total + Math.max(1, fighter.variants.length),
      0,
    ),
    wwii: FIGHTER_CATALOG.filter((fighter) => fighter.era === "World War II")
      .length,
    jets: FIGHTER_CATALOG.filter((fighter) => fighter.propulsion !== "piston")
      .length,
  };
}

export function fighterCatalogValidationIssues(): string[] {
  const issues: string[] = [];
  const ids = new Set<string>();
  for (const fighter of FIGHTER_CATALOG) {
    if (ids.has(fighter.id)) issues.push(`Duplicate fighter id: ${fighter.id}`);
    ids.add(fighter.id);
    if (!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(fighter.id)) {
      issues.push(`Invalid fighter id: ${fighter.id}`);
    }
    if (fighter.lengthM <= 0 || fighter.wingspanM <= 0) {
      issues.push(`${fighter.id}: dimensions must be positive`);
    }
    if (fighter.maxSpeedKph <= 0 || fighter.serviceCeilingM <= 0) {
      issues.push(`${fighter.id}: performance envelope must be positive`);
    }
    if (fighter.engines < 1 || fighter.crew < 1) {
      issues.push(`${fighter.id}: engines and crew must be positive`);
    }
    for (const referenceId of fighter.referenceIds) {
      if (!FIGHTER_DATA_REFERENCES[referenceId]) {
        issues.push(`${fighter.id}: unknown reference ${referenceId}`);
      }
    }
  }
  return issues;
}

const CATALOG_ISSUES = fighterCatalogValidationIssues();
if (CATALOG_ISSUES.length > 0) {
  throw new Error(`Invalid fighter catalog:\n${CATALOG_ISSUES.join("\n")}`);
}
